%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%{
%coded by Naoki Uchida
% last modification : 2023.2.6(by Ohta)
yTo Doz
Since the names of NMF data fold are slightly different between SesekiL and Yachimun, create a variable to deal with this.
(ex.)Yachimun ¨ 'new_nmf_result', SesekiL ¨ 'nmf_result'

yfunctionz
1.display trimmed temporal synergy (opereted time normalization) and save figures
saved location : easyData -> P-DATA -> (ex.)Ya170628toYa170929_47
2.merge save the data which is used to analyze x_corr(please correctly set specific var)
ycaution!!z
 please select all Pdata generated by MakeDataPlot_H_utb(Yachimun -> nmf_result -> synData¨Ya4~_Pdata.mat)
yprocedurez
pre : MakeDataForPlot_H_utb.m
post : calcXcorr.m(if you want to calculate & plot Xcorr) yplacez: /Volumes/Untitled/MATLAB/data/Yachimun/easyData/P-DATA(old filter TTakei delayed)
       or calcVAF.m(to calculate the contribution of each synergy)
(+a):When you want to check the H_synergy of each synergy cut out at each timing at once, use plotSynergy.m (contained in 'data' fold).
%}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% function [] = plotTarget()
clear
%% set param

%Pall(Lever1 on) : Averaged dataset on each session -50:150%(triggered at hold_on1)
%Ptrig1(Lever1 off) : Averaged dataset on each session -50:50%(triggered at hold_off1)
%Ptrig2 : Averaged dataset on each session -50:50%(triggered at hold_on2)
%Ptrig3 : Averaged dataset on each session -25:105%(triggered at hold_on1)

realname = 'Yachimun'; %monkey name
monkeyname = 'F';
Tar = 'EMG'; %the data which you want to plot -> 'EMG' 'Synergy' 'Synfixed'
% task = 'standard';
save_fold = 'easyData';
plot_fig = 1;               %
save_fig = 1;               %(if plot_fig == 1)save figures
save_fig_SD = 0;            %(if plot_fig == 1)save figures(average } SD)
pColor = 'K';               %select 'K'(black plot) or 'C'(color plot) yrecommend!!zpre-analysis:'K' post-analysis:'C'
save_data = 1;             %save cut data for calculating cross-correlation(each session)
save_end_control = 1;       %save cut data for calculating cross-correlation(Pre Data as a control data)
fontS = 5; % 10;                 %font size in figures 
LineW = 2.5; %0.1;                %width of plot line 
CTC = 0;                    %plot Cross Talk 
nomalizeAmp = 1;            %normalize Amplitude 
EachFigPlot = 'on';         %'on':display each muscle in different figures, 'off':use subplot and make one figure
YL = 3.0;                   % ylim of graph
save_xcorr_data = 0;        %save data to use of plot x_corr
restrict_disp = 0;           %Variables required to create the figures needed for the paper. Basically set to 0.
synergy_combination = 'dist-dist';

%% code section
%monkeyname‚É‚æ‚Á‚Ä•ªŠò
switch monkeyname
   case 'F'
      AVEPre4List = [1 2 3 4];%170516,170517,170524,170526 (same as synergy analysis )_Yachimun
      % plot window (Xcorr data will be made in this range)
      plotWindow1 = [-25 5];
      plotWindow2 = [-15 15];
      plotWindow3 = [-15 15];
      plotWindow4 = [95 125];
   case 'Ya'
      AVEPre4List = [1 2 3 4];%170516,170517,170524,170526 (same as synergy analysis )_Yachimun
      % plot window (Xcorr data will be made in this range)
      plotWindow1 = [-25 5];
      plotWindow2 = [-15 15];
      plotWindow3 = [-15 15];
      plotWindow4 = [95 125];
   case 'Se'
      AVEPre4List = [1 2 3];%200117,200119,200120 (same as synergy analysis )
      % plot window (Xcorr data will be made in this range)
      plotWindow1 = [-30 15];
      plotWindow2 = [-10 15];
      plotWindow3 = [-15 15];
      plotWindow4 = [98 115];
end
switch Tar
    case 'EMG'
%         YL = 100
        subN = 12; %subplot Num = number of EMG
%         disp(['yplease select all Pdata generated by MakeDataPlot_H_utb(' realname ' -> nmf_result -> synData¨YaSyn4~_Pdata.mat)z'])
        disp(['yplease select all Pdata.matz'])
        Allfiles_S = uigetfile('*.mat',...
                             'Select One or More Files', ...
                             'MultiSelect', 'on');
        if ischar(Allfiles_S)
            Allfiles_S = {Allfiles_S};
        end
        S = size(Allfiles_S);
    case 'Synergy'
%         YL = 2.2;
%         YL = 1.5;
        subN = 4; %subplot Num = num
        %please select all Pdata generated by MakeDataPlot_H_utb(Yachimun nmf_result synData¨Ya4~_Pdata.mat)
        disp(['yplease select all Pdata generated by MakeDataPlot_H_utb(' realname ' -> nmf_result -> synData¨YaSyn4~_Pdata.mat)z'])
        disp(['yplease select all Pdata.matz'])
        Allfiles_S = uigetfile('*.mat',...
                             'Select One or More Files', ...
                             'MultiSelect', 'on');
        if ischar(Allfiles_S)
            Allfiles_S = {Allfiles_S};
        end
        S = size(Allfiles_S);
end
Allfiles = strrep(Allfiles_S,'_Pdata.mat',''); 
AllDays = strrep(Allfiles,monkeyname,'');
if pColor == 'C'
    AllDaysN = strrep(AllDays,'Syn4','');
    AllDaysN =str2double(AllDaysN');
end
AllT_AVE = 0;
Pall.Tlist = zeros(S(2),1);
TaskT_AVE = 0;
TaskTlist = zeros(S(2),1);
D1_AVE = 0;
Ptrig1.Tlist = zeros(S(2),1);
D2_AVE = 0;
Ptrig2.Tlist = zeros(S(2),1);
D3_AVE = 0;
Ptrig3.Tlist = zeros(S(2),1);
% TimingPer = zeros(S(2),6);
% Timing.obj1s = zeros(S(2),6);
% Timing.obj1e = zeros(S(2),6);
% Timing.obj2s = zeros(S(2),6);
% Timing.obj2e = zeros(S(2),6);
cd([realname '/easyData/P-DATA'])
%% CT
%Daily variation of CrossTalk
if CTC == 1
for r = 1:S(2)%file=num loop
    load(Allfiles_S{r},'Yave','Y3ave');
    if r==1
        A = Yave;
        A3 = Y3ave;
    elseif r>1
        A(:,:,r) = Yave;
        A3(:,:,r) = Y3ave;
    end
    
end
%plot CT
f1 = figure('Position',[0 0 2000 1200]);
f2 = figure('Position',[0 0 2000 1200]);
for k=1:12
    figure(f1);
    for l=1:12
        subplot(12,12,l+(k-1)*12);
        hold on
        plot([0 S(2)],[0.25 0.25],'k');
        plot(reshape(A(13-k,l,:),1,[]),'LineWidth',1.5);
        Xe = find(reshape(A(13-k,l,:),1,[])>0.25);
        plot(Xe,reshape(A(13-k,l,Xe),1,[]),'ro','MarkerSize',2,'MarkerFaceColor','r');
        hold off
        ylim([0 1.2]);
        xlim([0 S(2)]);
    end
    figure(f2);
    for l=1:12
        subplot(12,12,l+(k-1)*12);
        hold on
        plot([0 S(2)],[0.25 0.25],'k');
        plot(reshape(A3(13-k,l,:),1,[]),'LineWidth',1.5);
         Xe = find(reshape(A3(13-k,l,:),1,[])>0.25);
        plot(Xe,reshape(A3(13-k,l,Xe),1,[]),'ro','MarkerSize',2,'MarkerFaceColor','r');
        hold off
        ylim([0 1.2]);
        xlim([0 S(2)]);
    end
end
SaveFig(f1,[realname 'CrossTalk'])
SaveFig(f2,[realname 'CrossTalk3rdDev'])
end
%% plot averaged Data
%get the average value of task time
for i = 1:S(2)
   switch Tar
    case {'EMG','EMG_NDfilt'}
        load(Allfiles_S{i},'AllT','Tp','TIME_W','D'); %AllT:all time
    case 'Synergy'
%         load(Allfiles_S{i},'Tp');
        cd ../../
        load_dir = 'nmf_result/synData/';
        load([load_dir monkeyname AllDays{i} '_Pdata.mat'],'AllT','TIME_W','D');
        cd('easyData/P-DATA')
    case 'Synfixed'
        load(Allfiles_S{i},'Tp');
        load([monkeyname 'Synfixed' AllDays{i} '_Pdata.mat'],'AllT','TIME_W','D');
   end
    %AllT
    AllT_AVE = (AllT_AVE*(i-1) + AllT)/i;
    Pall.Tlist(i,1) = AllT;
    %Tp
%     Tp2 = [Tp(:,2) Tp(:,2) Tp(:,2) Tp(:,2) Tp(:,2) Tp(:,2)];
%     Talt = mean(Tp - Tp2);
%     TimingPer(i,:) = Talt./Talt(5);
    %TIME_W
    TaskT_AVE = (TaskT_AVE*(i-1) + TIME_W)/i;
    TaskTlist(i,1) = TIME_W;
    %D.Ld1
    D1_AVE = (D1_AVE*(i-1) + D.Ld1)/i;
    Ptrig1.Tlist(i,1) = D.Ld1;
    %D.Ld2
    D2_AVE = (D2_AVE*(i-1) + D.Ld2)/i;
    Ptrig2.Tlist(i,1) = D.Ld2;
    %D.Ld3
    D3_AVE = (D3_AVE*(i-1) + D.Ld3)/i;
    Ptrig3.Tlist(i,1) = D.Ld3;
end
Pall.AllT_AVE = round(AllT_AVE);
TaskT_AVE = round(TaskT_AVE);
Ptrig1.AllT_AVE = round(D1_AVE);
Ptrig2.AllT_AVE = round(D2_AVE);
Ptrig3.AllT_AVE = round(D3_AVE);
%cd ../../
% load(Allfiles_S{i},'taskRange');
Pall.plotData_sel = cell(S(2),1);
Ptrig1.plotData_sel = cell(S(2),1);
Ptrig2.plotData_sel = cell(S(2),1);
Ptrig3.plotData_sel = cell(S(2),1);
sec = zeros(3,1);
%%%%%%%%%%%%%%    nomalize data   %%%%%%%%%%%%%%
%%%  ALL  %%%
for j = 1:S(2)%file=num loop
    switch Tar
        case {'EMG','EMG_NDfilt'}
            load(Allfiles_S{j},'alignedDataAVE');
            load([monkeyname AllDays{j} '_dataTrig' Tar '.mat'],'alignedData_all');
            [trigData, slct_all_trial] = AlignDatasets(alignedData_all,Pall.AllT_AVE ,'row');
            Pall.trigData_sel{j,1} = trigData;
        case 'Synergy'
            cd ../../
            load([load_dir monkeyname AllDays{j} '_Pdata.mat'],'alignedDataAVE');
            cd 'easyData/P-DATA'
        case 'Synfixed'
            load([monkeyname 'Synfixed' AllDays{j} '_Pdata.mat'],'alignedDataAVE');
    end
    Sk = size(alignedDataAVE); %synergy(or EMG) num
%     plotData = zeros(Sk(2),Pall.AllT_AVE);
    [plotData, slct_all_ave] = AlignDatasets(alignedDataAVE,Pall.AllT_AVE ,'row');
%         for k = 1:Sk(2)%EMG_num loop 
%             sec(1,1) = sec(1,1)+1;
%             plotData(k,:) = alignedDataAVE{1,k};
%             trigData(k,:) = alignedData_all{1,k};
%         end
%     elseif Pall.Tlist(j,1)<Pall.AllT_AVE 
%         for k = 1:Sk(2)%EMG_num loop 
%             sec(2,1) = sec(2,1)+1;
%             plotData(k,:) = interpft(alignedDataAVE{1,k},Pall.AllT_AVE);
%         end
%     else
%         for k = 1:Sk(2)%EMG_num loop 
%             sec(3,1) = sec(3,1)+1;
%             plotData(k,:) = resample(alignedDataAVE{1,k},Pall.AllT_AVE,Pall.Tlist(j,1));
%         end
%     end
    if nomalizeAmp
       for mm = 1:Sk(2)          
          %plotData(mm,:) = plotData(mm,:)./max(plotData(mm,:));
          plotData{mm} = plotData{mm}./max(plotData{mm});
          %trigData(mm,:) = trigData(mm,:)./max(trigData(mm,:));
          %trigData{mm} = trigData{mm}./max(trigData{mm});
          
       end
    end
    Pall.plotData_sel{j,1} = plotData;
%     Pall.trigData_sel{j,1} = trigData;
end
%%%  trig obj1 end  %%%
for j = 1:S(2)%file=num loop
    switch Tar
    case {'EMG','EMG_NDfilt'}
        load(Allfiles_S{j},'ResAVE');
        load([monkeyname AllDays{j} '_dataTrig' Tar '.mat'],'alignedData_trial');
    case 'Synergy'
        cd ../../
        load([load_dir monkeyname AllDays{j} '_Pdata.mat'],'ResAVE'); 
        cd 'easyData/P-DATA'
    case 'Synfixed'
        load([monkeyname 'Synfixed' AllDays{j} '_Pdata.mat'],'ResAVE');
    end
    Sk = size(ResAVE.tData1_AVE);
    plotData = zeros(Sk(2),Ptrig1.AllT_AVE);
    if Ptrig1.Tlist(j,1) == Ptrig1.AllT_AVE
        for k = 1:Sk(2)%EMG_num loop 
            sec(1,1) = sec(1,1)+1;
            plotData(k,:) = ResAVE.tData1_AVE{1,k};
        end
    elseif Ptrig1.Tlist(j,1)<Ptrig1.AllT_AVE 
        for k = 1:Sk(2)%EMG_num loop 
            sec(2,1) = sec(2,1)+1;
            plotData(k,:) = interpft(ResAVE.tData1_AVE{1,k},Ptrig1.AllT_AVE);
        end
    else
        for k = 1:Sk(2)%EMG_num loop 
            sec(3,1) = sec(3,1)+1;
            plotData(k,:) = resample(ResAVE.tData1_AVE{1,k},Ptrig1.AllT_AVE,Ptrig1.Tlist(j,1));
        end
    end
    if nomalizeAmp
       for mm = 1:Sk(2)
         plotData(mm,:) = plotData(mm,:)./max(plotData(mm,:));
       end
    end
    Ptrig1.plotData_sel{j,1} = plotData;
end
%%%  trig obj2 start  %%%
for j = 1:S(2)%file=num loop
    switch Tar
    case {'EMG','EMG_NDfilt'}
        load(Allfiles_S{j},'ResAVE');
        load([monkeyname AllDays{j} '_dataTrig' Tar '.mat'],'alignedData_trial');
    case 'Synergy'
        cd ../../
        load([load_dir monkeyname AllDays{j} '_Pdata.mat'],'ResAVE');
        cd 'easyData/P-DATA'
    case 'Synfixed'
        load([monkeyname 'Synfixed' AllDays{j} '_Pdata.mat'],'ResAVE');
    end
    Sk = size(ResAVE.tData2_AVE);
    plotData = zeros(Sk(2),Ptrig2.AllT_AVE);
    if Ptrig2.Tlist(j,1) == Ptrig2.AllT_AVE
        for k = 1:Sk(2)%EMG_num loop 
            sec(1,1) = sec(1,1)+1;
            plotData(k,:) = ResAVE.tData2_AVE{1,k};
        end
    elseif Ptrig2.Tlist(j,1)<Ptrig2.AllT_AVE 
        for k = 1:Sk(2)%EMG_num loop 
            sec(2,1) = sec(2,1)+1;
            plotData(k,:) = interpft(ResAVE.tData2_AVE{1,k},Ptrig2.AllT_AVE);
        end
    else
        for k = 1:Sk(2)%EMG_num loop 
            sec(3,1) = sec(3,1)+1;
            plotData(k,:) = resample(ResAVE.tData2_AVE{1,k},Ptrig2.AllT_AVE,Ptrig2.Tlist(j,1));
        end
    end
    if nomalizeAmp
       for mm = 1:Sk(2)
         plotData(mm,:) = plotData(mm,:)./max(plotData(mm,:));
       end
    end
    Ptrig2.plotData_sel{j,1} = plotData;
end
%%%  trig 1task start  %%%
for j = 1:S(2)%file=num loop
    switch Tar
    case {'EMG','EMG_NDfilt'}
        load(Allfiles_S{j},'ResAVE');
        load([monkeyname AllDays{j} '_dataTrig' Tar '.mat'],'alignedData_trial');
    case 'Synergy'
        cd ../../
        load([load_dir monkeyname AllDays{j} '_Pdata.mat'],'ResAVE');
        cd 'easyData/P-DATA'
    case 'Synfixed'
        load([monkeyname 'Synfixed' AllDays{j} '_Pdata.mat'],'ResAVE');
    end
    Sk = size(ResAVE.tData3_AVE);
    plotData = zeros(Sk(2),Ptrig3.AllT_AVE);
    if Ptrig3.Tlist(j,1) == Ptrig3.AllT_AVE
        for k = 1:Sk(2)%EMG_num loop 
            sec(1,1) = sec(1,1)+1;
            plotData(k,:) = ResAVE.tData3_AVE{1,k};
        end
    elseif Ptrig3.Tlist(j,1)<Ptrig3.AllT_AVE 
        for k = 1:Sk(2)%EMG_num loop 
            sec(2,1) = sec(2,1)+1;
            plotData(k,:) = interpft(ResAVE.tData3_AVE{1,k},Ptrig3.AllT_AVE);
        end
    else
        for k = 1:Sk(2)%EMG_num loop 
            sec(3,1) = sec(3,1)+1;
            plotData(k,:) = resample(ResAVE.tData3_AVE{1,k},Ptrig3.AllT_AVE,Ptrig3.Tlist(j,1));
        end
    end
    if nomalizeAmp
       for mm = 1:Sk(2)
         plotData(mm,:) = plotData(mm,:)./max(plotData(mm,:));
       end
    end
    Ptrig3.plotData_sel{j,1} = plotData;
end

switch Tar
    case 'EMG'
        load(Allfiles_S{1},'EMGs','taskRange');
    case 'Synergy'
        cd ../../
        load(['nmf_result/synData/' Allfiles_S{1}],'taskRange');
        cd easyData/P-DATA
end
% P = load('PostDays.mat');
% PostDays = P.PostDays(6:end);%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Sp = length(PostDays);
% SpYa = length(P.PostDaysYa);
% Csp = jet(SpYa);
% cd ../

switch pColor
   case 'C'
      P = load('PostDays.mat');
      switch monkeyname
         case 'Ya'
            PostDays = P.PostDays;
            Sp = length(PostDays);
            Csp = zeros(Sp,3);
            Csp(:,1) = ones(Sp,1).*linspace(0.3,1,Sp)';
         case 'Se'
            PostDays = P.PostDays(6:end);
            Sp = length(PostDays);
            Csp = zeros(Sp,3);
            Csp(:,2) = ones(Sp,1).*linspace(0.3,1,Sp)';
         case 'Ma'
            PostDays = P.PostDays;
            Sp = length(PostDays);
            Csp = zeros(Sp,3);
            Csp(:,1) = ones(Sp,1).*linspace(0.3,1,Sp)';
      end
   case 'K'
      
end
%make data for SD plot
SDdata = cell(S(2),1);
Pall.SD = cell(Sk(2),1);
Pall.AVE = cell(Sk(2),1);
for m = 1:Sk(2)
   for d = 1:S(2)
      SDdata{d} = cell2mat(Pall.plotData_sel{d,1}(m,:));
   end
   Pall.SD{m} = std(cell2mat(SDdata),1,1);
   Pall.AVE{m} = mean(cell2mat(SDdata),1);
end
Ptrig1.SD = cell(Sk(2),1);
for m = 1:Sk(2)
   for d = 1:S(2)
      SDdata{d} = Ptrig1.plotData_sel{d,1}(m,:);
   end
   Ptrig1.SD{m} = std(cell2mat(SDdata),1,1);
   Ptrig1.AVE{m} = mean(cell2mat(SDdata),1);
end
Ptrig2.SD = cell(Sk(2),1);
for m = 1:Sk(2)
   for d = 1:S(2)
      SDdata{d} = Ptrig2.plotData_sel{d,1}(m,:);
   end
   Ptrig2.SD{m} = std(cell2mat(SDdata),1,1);
   Ptrig2.AVE{m} = mean(cell2mat(SDdata),1);
end
for m = 1:Sk(2)
   for d = 1:S(2)
      SDdata{d} = Ptrig3.plotData_sel{d,1}(m,:);
   end
   Ptrig3.SD{m} = std(cell2mat(SDdata),1,1);
   Ptrig3.AVE{m} = mean(cell2mat(SDdata),1);
end

%save data for calculating cross-correlation
if save_data==1
    %he range of data cutting
    cutWin1 = round((plotWindow1./100).*TaskT_AVE + Pall.AllT_AVE/4);
    cutWin2 = round((plotWindow2./100).*TaskT_AVE + Ptrig1.AllT_AVE/2);
    cutWin3 = round((plotWindow3./100).*TaskT_AVE + Ptrig2.AllT_AVE/2);
    cutWin4 = round((plotWindow4./100).*TaskT_AVE + Pall.AllT_AVE/4);
    %X-corr Data
    TrigData_Each.T1.data = cell(S);
    TrigData_Each.T2.data = cell(S);
    TrigData_Each.T3.data = cell(S);
    TrigData_Each.T4.data = cell(S);
    %ŽŸ‚Ìmake struct data‚ªs‚¦‚é‚æ‚¤‚ÉAƒf[ƒ^\‘¢‚ð•ÏX‚·‚é
    for j = 1:S(2)
        Pall.plotData_sel{j} = cell2mat(Pall.plotData_sel{j});
    end
    %make struct data 
    for j = 1:S(2)
    %
%         TrigData_Each.T1.data{j} = Pall.plotData_sel{1,1}{j}(:,cutWin1(1)+1:cutWin1(2));
        TrigData_Each.T1.data{j} = Pall.plotData_sel{j}(:,cutWin1(1)+1:cutWin1(2));
        TrigData_Each.T2.data{j} = Ptrig2.plotData_sel{j}(:,cutWin2(1)+1:cutWin2(2));
        TrigData_Each.T3.data{j} = Ptrig3.plotData_sel{j}(:,cutWin3(1)+1:cutWin3(2));
%         TrigData_Each.T4.data{j} = Pall.plotData_sel{1,1}{j}(:,cutWin4(1)+1:cutWin4(2));
        TrigData_Each.T4.data{j} = Pall.plotData_sel{j}(:,cutWin4(1)+1:cutWin4(2));
    end
    %make end-control data (4days) Only Yachimun
    if (save_end_control==1)
        TrigData_Each.T1.AVEend4 = (TrigData_Each.T1.data{S(2)} + TrigData_Each.T1.data{S(2)-1} + TrigData_Each.T1.data{S(2)-2} + TrigData_Each.T1.data{S(2)-3})./4;
        TrigData_Each.T2.AVEend4 = (TrigData_Each.T2.data{S(2)} + TrigData_Each.T2.data{S(2)-1} + TrigData_Each.T2.data{S(2)-2} + TrigData_Each.T2.data{S(2)-3})./4;
        TrigData_Each.T3.AVEend4 = (TrigData_Each.T3.data{S(2)} + TrigData_Each.T3.data{S(2)-1} + TrigData_Each.T3.data{S(2)-2} + TrigData_Each.T3.data{S(2)-3})./4;
        TrigData_Each.T4.AVEend4 = (TrigData_Each.T4.data{S(2)} + TrigData_Each.T4.data{S(2)-1} + TrigData_Each.T4.data{S(2)-2} + TrigData_Each.T4.data{S(2)-3})./4;
        if S(2)==80
             TrigData_Each.T1.AVEPre4 = (TrigData_Each.T1.data{AVEPre4List(1)} + TrigData_Each.T1.data{AVEPre4List(2)} + TrigData_Each.T1.data{AVEPre4List(3)} + TrigData_Each.T1.data{AVEPre4List(4)})./4;
             TrigData_Each.T2.AVEPre4 = (TrigData_Each.T2.data{AVEPre4List(1)} + TrigData_Each.T2.data{AVEPre4List(2)} + TrigData_Each.T2.data{AVEPre4List(3)} + TrigData_Each.T2.data{AVEPre4List(4)})./4;
             TrigData_Each.T3.AVEPre4 = (TrigData_Each.T3.data{AVEPre4List(1)} + TrigData_Each.T3.data{AVEPre4List(2)} + TrigData_Each.T3.data{AVEPre4List(3)} + TrigData_Each.T3.data{AVEPre4List(4)})./4;
             TrigData_Each.T4.AVEPre4 = (TrigData_Each.T4.data{AVEPre4List(1)} + TrigData_Each.T4.data{AVEPre4List(2)} + TrigData_Each.T4.data{AVEPre4List(3)} + TrigData_Each.T4.data{AVEPre4List(4)})./4;
             TrigData_Each.AVEPre4List = AVEPre4List;
        end
        if or(S(2)==51, S(2)==37)
             TrigData_Each.T1.AVEPre4 = (TrigData_Each.T1.data{AVEPre4List(1)} + TrigData_Each.T1.data{AVEPre4List(2)} + TrigData_Each.T1.data{AVEPre4List(3)} + TrigData_Each.T1.data{AVEPre4List(4)})./4;
             TrigData_Each.T2.AVEPre4 = (TrigData_Each.T2.data{AVEPre4List(1)} + TrigData_Each.T2.data{AVEPre4List(2)} + TrigData_Each.T2.data{AVEPre4List(3)} + TrigData_Each.T2.data{AVEPre4List(4)})./4;
             TrigData_Each.T3.AVEPre4 = (TrigData_Each.T3.data{AVEPre4List(1)} + TrigData_Each.T3.data{AVEPre4List(2)} + TrigData_Each.T3.data{AVEPre4List(3)} + TrigData_Each.T3.data{AVEPre4List(4)})./4;
             TrigData_Each.T4.AVEPre4 = (TrigData_Each.T4.data{AVEPre4List(1)} + TrigData_Each.T4.data{AVEPre4List(2)} + TrigData_Each.T4.data{AVEPre4List(3)} + TrigData_Each.T4.data{AVEPre4List(4)})./4;
             TrigData_Each.AVEPre4List = AVEPre4List;
        end
        if S(2)==50
             TrigData_Each.T1.AVEPre4 = (TrigData_Each.T1.data{AVEPre4List(1)} + TrigData_Each.T1.data{AVEPre4List(2)} + TrigData_Each.T1.data{AVEPre4List(3)} + TrigData_Each.T1.data{AVEPre4List(4)})./4;
             TrigData_Each.T2.AVEPre4 = (TrigData_Each.T2.data{AVEPre4List(1)} + TrigData_Each.T2.data{AVEPre4List(2)} + TrigData_Each.T2.data{AVEPre4List(3)} + TrigData_Each.T2.data{AVEPre4List(4)})./4;
             TrigData_Each.T3.AVEPre4 = (TrigData_Each.T3.data{AVEPre4List(1)} + TrigData_Each.T3.data{AVEPre4List(2)} + TrigData_Each.T3.data{AVEPre4List(3)} + TrigData_Each.T3.data{AVEPre4List(4)})./4;
             TrigData_Each.T4.AVEPre4 = (TrigData_Each.T4.data{AVEPre4List(1)} + TrigData_Each.T4.data{AVEPre4List(2)} + TrigData_Each.T4.data{AVEPre4List(3)} + TrigData_Each.T4.data{AVEPre4List(4)})./4;
             TrigData_Each.AVEPre4List = AVEPre4List;
        end
        
        if S(2)==28
             TrigData_Each.T1.AVEPre4 = (TrigData_Each.T1.data{AVEPre4List(1)} + TrigData_Each.T1.data{AVEPre4List(2)} + TrigData_Each.T1.data{AVEPre4List(3)})./3;
             TrigData_Each.T2.AVEPre4 = (TrigData_Each.T2.data{AVEPre4List(1)} + TrigData_Each.T2.data{AVEPre4List(2)} + TrigData_Each.T2.data{AVEPre4List(3)})./3;
             TrigData_Each.T3.AVEPre4 = (TrigData_Each.T3.data{AVEPre4List(1)} + TrigData_Each.T3.data{AVEPre4List(2)} + TrigData_Each.T3.data{AVEPre4List(3)})./3;
             TrigData_Each.T4.AVEPre4 = (TrigData_Each.T4.data{AVEPre4List(1)} + TrigData_Each.T4.data{AVEPre4List(2)} + TrigData_Each.T4.data{AVEPre4List(3)})./3; 
             TrigData_Each.AVEPre4List = AVEPre4List;
        end
    end
end

%make alighned data on obj1end and obj2start
% perR1e = [30 30];
% perR2s = [30 30];
% obj1e.RangeN = [sum(perR1e)+1, perR1e(1)/100, perR1e(2)/100];
% obj2s.RangeN = [sum(perR2s)+1, perR2s(1)/100, perR2s(2)/100];
% obj1e.Trig = zeros(S);
% obj2s.Trig = zeros(S);
% obj1e.pData = zeros(obj1e.RangeN);
% for j = 1:S(2)%file=num loop
%     obj1e.Trig(j) = round(TaskT_AVE*(abs(taskRange(1))+TimingPer(j,3)));
%     obj2s.Trig(j) = round(TaskT_AVE*(abs(taskRange(1))+TimingPer(j,4)));
%     obj1e.pData(j,:) = ;
% end
% load([realname 'PostFiles.mat']);
mkdir([ Allfiles{1} 'to' Allfiles{end} '_' sprintf('%d',S(end))]);
cd([ Allfiles{1} 'to' Allfiles{end} '_' sprintf('%d',S(end))]);
Pall.x = linspace(taskRange(1),taskRange(2),Pall.AllT_AVE);
Ptrig1.x = linspace(-D.Range1(1),D.Range1(2),Ptrig1.AllT_AVE);
Ptrig2.x = linspace(-D.Range2(1),D.Range2(2),Ptrig2.AllT_AVE);
Ptrig3.x = linspace(-D.Range3(1),D.Range3(2),Ptrig3.AllT_AVE);
% c = jet(45);%45days : the number of days after TT

%% plot figure
disp('start %%%%%%%%%%%%%%%% PLOT DATA %%%%%%%%%%%%%%%%')
%%%%%%%%%%%%%%%% PLOT DATA %%%%%%%%%%%%%%%%
if plot_fig == 1
    Fsub = cell(12,4); % for saving subplot configuration
    FsubS = cell(12,4); % for saving subplot configuration (for SD plot)
    %Fig1Task = figure('Position',[700 720 600 400]);
    if pColor=='K'
       Fig1TaskSD = figure('Position',[700 720 600 400]);
    end
    %figure(plot Pall Data(ƒ^ƒXƒNŠJŽn‚©‚ç-25% - 105%‚Ì})); %ƒvƒƒbƒg‚µ‚½ƒf[ƒ^‚ð•Û‘¶‚à‚¹‚¸‚Éclose all‚µ‚Ä‚¢‚é.‰½‚ð‚µ‚½‚©‚Á‚½‚Ì‚©•s–¾
    for m = 1:Sk(2)%EMG_num loop 
       switch EachFigPlot
          case 'on'
             figure('Position',[0 720 600 400])         %plot data in 12 figures
          case 'off'
             subplot(subN,4,m)                             %plot data in one figure   
       end
       hold on
       c = jet(S(2));
    %    c = cool(S(2));
       for d = 1:S(2)%file=num loop
    %     plot(Pall.x,Pall.plotData_sel{d,1}(m,:),'Color',c(find(PostFiles{1,:}==Allfiles(d)),:),'LineWidth',LineW);
          switch pColor
             case 'C'
                 try
    %              plot(Pall.x,Pall.plotData_sel{d,1}(m,:),'Color',c(d,:),'LineWidth',LineW);
                    plot(Pall.x,cell2mat(Pall.plotData_sel{d,1}(m,:)),'Color',Csp(find(PostDays==AllDaysN(d)),:),'LineWidth',LineW);
                 catch
                    plot(Pall.x,Pall.plotData_sel{d,1}(m,:),'Color',Csp(find(PostDays==AllDaysN(d)),:),'LineWidth',LineW);
                 end
             case 'K'
                 try
                    plot(Pall.x,cell2mat(Pall.plotData_sel{d,1}(m,:)),'k','LineWidth',LineW);
                 catch
                    plot(Pall.x,Pall.plotData_sel{d,1}(m,:),'k','LineWidth',LineW);
                 end
          end
       end
      
    %    
    %    plot([100 100],[0 160],'-r','LineWidth',LineW);
    %        title([EMGs{m,1} Allfiles{1,d}],'FontSize',25);
    %    plot([0 0],[0 160],'-r');
    %    plot([100 100],[0 160],'-r');
       hold off
       if nomalizeAmp == 1
          ylim([0 1]);
       else
          ylim([0 YL]);
       end
       xlim([-25 105]);
    %    title(EMGs{m,1},'FontSize',fontS);
       if save_fig == 1
    %        saveas(gcf,[EMGs{m,1} '_' Allfiles{1} 'to' Allfiles{end} '_' sprintf('%d',S(end)) '.epsc']);
    %        saveas(gcf,[EMGs{m,1} '_' Allfiles{1} 'to' Allfiles{end} '_' sprintf('%d',S(end)) '.png']);
    %        saveas(gcf,[EMGs{m,1} '_' Allfiles{1} 'to' Allfiles{end} '_' sprintf('%d',S(end)) '.fig']);
       end
       close gcf
       if pColor=='K'
          figure(Fig1TaskSD);
          sd = Pall.SD{m};
          y = Pall.AVE{m};
          xconf = [Pall.x Pall.x(end:-1:1)];
          yconf = [y+sd y(end:-1:1)-sd(end:-1:1)];
          subplot(subN,4,m)
          hold on;
          fi = fill(xconf,yconf,'k');
          fi.FaceColor = [0.8 0.8 1];       % make the filled area pink
          fi.EdgeColor = 'none';            % remove the line around the filled area
          plot(Pall.x,y,'k','LineWidth',LineW);
          xline(0,'color','r','LineWidth',LineW)
%           plot([100 100],[0 160],'-r','LineWidth',LineW);
          hold off;
          if nomalizeAmp == 1
             ylim([0 1]);
          else
             ylim([0 YL]);
          end
          xlim([-25 105]); 
          %figure(Fig1Task);
       end
    end
    %new aligned plot
    % Fsub = cell(12,4); % for saving subplot configuration
    FigTrigAll = figure('Position',[0 0 700 1200]);
    if pColor=='K'
       FigTrigSD = figure('Position',[0 0 700 1200]);
    end
    % TRIG1(lever1 on•t‹ß)
    figure(FigTrigAll);
    for m = 1:Sk(2)%EMG_num loop 
       switch EachFigPlot
          case 'on'
             Fsub{m,1} = figure('Position',[0 720 600 400]);
             switch Tar
                 case 'EMG'
                     title(['tirg1 ' EMGs{m,1}],'FontName', 'Arial','FontWeight', 'bold')
                 case 'Synergy'
                     title(['tirg1 Synergy' sprintf('%d',m)],'FontName', 'Arial','FontWeight', 'bold')
                 case 'Synfixed'
                     title(['tirg1 Synergy' sprintf('%d',m)],'FontName', 'Arial','FontWeight', 'bold')
             end
          case 'off'
             f = subplot(subN,4,4*(m-1)+1);
             f.FontSize = 5;
       end
       hold on
       c = jet(S(2));
    %    c = cool(S(2));
       for d = 1:S(2)%file=num loop
    %     plot(Pall.x,Pall.plotData_sel{d,1}(m,:),'Color',c(find(PostFiles{1,:}==Allfiles(d)),:),'LineWidth',LineW);
          switch pColor
             case 'C'
                try
                    plot(Pall.x,cell2mat(Pall.plotData_sel{d,1}(m,:)),'Color',Csp(find(PostDays==AllDaysN(d)),:),'LineWidth',LineW);
                catch
                    plot(Pall.x,Pall.plotData_sel{d,1}(m,:),'Color',Csp(find(PostDays==AllDaysN(d)),:),'LineWidth',LineW);
                end
             case 'K'
                try
                    plot(Pall.x,cell2mat(Pall.plotData_sel{d,1}(m,:)),'k','LineWidth',LineW);
                catch
                    plot(Pall.x,Pall.plotData_sel{d,1}(m,:),'k','LineWidth',LineW);
                end
          end
       end
       xline(0,'color','r','LineWidth',LineW)
       %xline(0,'color','r','LineWidth',LineW)
    %    plot([100 100],[0 160],'-r','LineWidth',LineW);

    %        title([EMGs{m,1} Allfiles{1,d}],'FontSize',25);
    %    xline(0,'color','r','LineWidth',LineW)
    %    plot([100 100],[0 160],'-r','LineWidth',LineW);
       hold off
       if nomalizeAmp == 1
          ylim([0 1]);
       else
          ylim([0 YL]);
       end
       xlim(plotWindow1);
    %    title(EMGs{m,1},'FontSize',fontS);
       if save_fig == 1
           xlabel('task range [%]')
              ylabel('coefficient')
              a = gca;
              a.FontSize = 20;
              a.FontWeight = 'bold';
              a.FontName = 'Arial';
              saveas(gcf,[Tar sprintf('%d',m) '_' Allfiles{1} 'to' Allfiles{end} '_Trig1_' sprintf('%d',S(end)) '.fig']);
              saveas(gcf,[Tar sprintf('%d',m) '_' Allfiles{1} 'to' Allfiles{end} '_Trig1_' sprintf('%d',S(end)) '.png']);
    %        saveas(gcf,[EMGs{m,1} '_' Allfiles{1} 'to' Allfiles{end} '_' sprintf('%d',S(end)) '.epsc']);
    %          saveas(gcf,[EMGs{m,1} '_' Allfiles{1} 'to' Allfiles{end} '_' sprintf('%d',S(end)) '.png']);
    %        saveas(gcf,[EMGs{m,1} '_' Allfiles{1} 'to' Allfiles{end} '_' sprintf('%d',S(end)) '.fig']);
       end
       if pColor=='K'
          figure(FigTrigSD);
          sd = Pall.SD{m};
          y = Pall.AVE{m};
          xconf = [Pall.x Pall.x(end:-1:1)];
          yconf = [y+sd y(end:-1:1)-sd(end:-1:1)];
          switch EachFigPlot
             case 'on'
                FsubS{m,1} = figure('Position',[0 720 600 400]);
             case 'off'
                fsd = subplot(subN,4,4*(m-1)+1);
                fsd.FontSize = 5;
          end
          hold on;
          fi = fill(xconf,yconf,'k');
          fi.FaceColor = [0.8 0.8 1];       % make the filled area pink
          fi.EdgeColor = 'none';            % remove the line around the filled area
          plot(Pall.x,y,'k','LineWidth',LineW);
    %       xline(0,'color','r','LineWidth',LineW)
    %       plot([100 100],[0 160],'-r','LineWidth',LineW);
          title(['tirg1 Synergy' sprintf('%d',m)],'FontName', 'Arial','FontWeight', 'bold')
          hold off;
          if nomalizeAmp == 1
             ylim([0 1]);
          else
             ylim([0 YL]);
          end
          xlim(plotWindow1); 
          if save_fig_SD == 1
              xlabel('task range [%]')
              ylabel('coefficient')
              a = gca;
              a.FontSize = 20;
              a.FontWeight = 'bold';
              a.FontName = 'Arial';
              saveas(gcf,[Tar sprintf('%d',m) '_' Allfiles{1} 'to' Allfiles{end} '_Trig1_' sprintf('%d',S(end)) '_SD.fig']);
              saveas(gcf,[Tar sprintf('%d',m) '_' Allfiles{1} 'to' Allfiles{end} '_Trig1_' sprintf('%d',S(end)) '_SD.png']);
          end
          figure(FigTrigAll);
       end
    end
    % TRIG2(lever1 off)
    for m = 1:Sk(2)%EMG_num loop 
       switch EachFigPlot
          case 'on'
             Fsub{m,2} = figure('Position',[600 720 600 400]);
             switch Tar
                 case 'EMG'
                     title(['tirg2 ' EMGs{m,1}],'FontName', 'Arial','FontWeight', 'bold')
                 case 'Synergy'
                     title(['tirg2 Synergy' sprintf('%d',m)],'FontName', 'Arial','FontWeight', 'bold')
                 case 'Synfixed'
                     title(['tirg2 Synergy' sprintf('%d',m)],'FontName', 'Arial','FontWeight', 'bold')
             end
          case 'off'
             f = subplot(subN,4,4*(m-1)+2);
             f.FontSize = 5;
       end
       hold on
       c = jet(S(2));
    %    c = cool(S(2));
       for d = 1:S(2)%file=num loop
    %     plot(Ptrig1.x,Ptrig1.plotData_sel{d,1}(m,:),'Color',c(find(PostFiles{1,:}==Allfiles(d)),:),'LineWidth',LineW);
          switch pColor
             case 'C'
    %              plot(Ptrig1.x,Ptrig1.plotData_sel{d,1}(m,:),'Color',c(d,:),'LineWidth',LineW);
                 plot(Ptrig2.x,Ptrig2.plotData_sel{d,1}(m,:),'Color',Csp(find(PostDays==AllDaysN(d)),:),'LineWidth',LineW);
             case 'K'
                 plot(Ptrig2.x,Ptrig2.plotData_sel{d,1}(m,:),'k','LineWidth',LineW);
          end
           xline(0,'color','r','LineWidth',LineW)
           xline(0,'color','r','LineWidth',LineW)
    %        plot([100 100],[0 160],'-r','LineWidth',LineW);
    %        title([EMGs{m,1} Allfiles{1,d}],'FontSize',fontS);
       end
    %    plot([0 0],[0 160],'-r');
    %    plot([100 100],[0 160],'-r');
       hold off
       if nomalizeAmp == 1
          ylim([0 1]);
       else
          ylim([0 YL]);
       end
    %    xlim([-D.Range1(1) D.Range1(2)]);
       xlim(plotWindow2)
    %    title(EMGs{m,1},'FontSize',fontS);
       if save_fig == 1
           xlabel('task range [%]')
              ylabel('coefficient')
              a = gca;
              a.FontSize = 20;
              a.FontWeight = 'bold';
              a.FontName = 'Arial';
              saveas(gcf,[Tar sprintf('%d',m) '_' Allfiles{1} 'to' Allfiles{end} '_Trig2_' sprintf('%d',S(end)) '.fig']);
              saveas(gcf,[Tar sprintf('%d',m) '_' Allfiles{1} 'to' Allfiles{end} '_Trig2_' sprintf('%d',S(end)) '.png']);
    %        saveas(gcf,[EMGs{m,1} '_' Allfiles{1} 'to' Allfiles{end} '_Trig1_' sprintf('%d',S(end)) '.epsc']);
    %          saveas(gcf,[EMGs{m,1} '_' Allfiles{1} 'to' Allfiles{end} '_Trig1_' sprintf('%d',S(end)) '.png']);
    %        saveas(gcf,[EMGs{m,1} '_' Allfiles{1} 'to' Allfiles{end} '_Trig1_' sprintf('%d',S(end)) '.fig']);
       end
       if pColor=='K'
          figure(FigTrigSD);
          sd = Ptrig2.SD{m};
          y = Ptrig2.AVE{m};
          xconf = [Ptrig2.x Ptrig2.x(end:-1:1)];
          yconf = [y+sd y(end:-1:1)-sd(end:-1:1)];
          switch EachFigPlot
             case 'on'
                FsubS{m,2} = figure('Position',[600 720 600 400]);
             case 'off'
                fsd = subplot(subN,4,4*(m-1)+2);
                fsd.FontSize = 5;
          end
          hold on;
          fi = fill(xconf,yconf,'k');
          fi.FaceColor = [0.8 0.8 1];       % make the filled area pink
          fi.EdgeColor = 'none';            % remove the line around the filled area
          plot(Ptrig2.x,y,'k','LineWidth',LineW);
          xline(0,'color','r','LineWidth',LineW)
%           plot([100 100],[0 160],'-r','LineWidth',LineW);
          title(['tirg2 Synergy' sprintf('%d',m)],'FontName', 'Arial','FontWeight', 'bold')
          hold off;
          if nomalizeAmp == 1
             ylim([0 1]);
          else
             ylim([0 YL]);
          end
          xlim(plotWindow2); 
          if save_fig_SD == 1
              xlabel('task range [%]')
              ylabel('coefficient')
              a = gca;
              a.FontSize = 20;
              a.FontWeight = 'bold';
              a.FontName = 'Arial';
              saveas(gcf,[Tar sprintf('%d',m) '_' Allfiles{1} 'to' Allfiles{end} '_Trig2_' sprintf('%d',S(end)) '_SD.fig']);
              saveas(gcf,[Tar sprintf('%d',m) '_' Allfiles{1} 'to' Allfiles{end} '_Trig2_' sprintf('%d',S(end)) '_SD.png']);
          end
          figure(FigTrigAll);
       end
    end
    % TRIG3
    for m = 1:Sk(2)%EMG_num loop 
       switch EachFigPlot
          case 'on'
             Fsub{m,3} = figure('Position',[1200 720 600 400]);
             switch Tar
                 case 'EMG'
                     title(['trig3 ' EMGs{m,1}],'FontName', 'Arial','FontWeight', 'bold')
                 case 'Synergy'
                     if restrict_disp == 1
                         title(['photo on Synergy' sprintf('%d',m)],'FontName', 'Arial','FontWeight', 'bold')
                     else
                         title(['trig3 Synergy' sprintf('%d',m)],'FontName', 'Arial','FontWeight', 'bold')
                     end
                 case 'Synfixed'
                     title(['trig3 Synergy' sprintf('%d',m)],'FontName', 'Arial','FontWeight', 'bold')
             end
          case 'off'
             f = subplot(subN,4,4*(m-1)+3);
             f.FontSize = 5;
       end
       hold on
       c = jet(S(2));
    %    c = cool(S(2));
       for d = 1:S(2)%file=num loop
    %     plot(Ptrig2.x,Ptrig2.plotData_sel{d,1}(m,:),'Color',c(find(PostFiles{1,:}==Allfiles(d)),:),'LineWidth',LineW);
           if restrict_disp == 1
               %«ŒÂ•Ê‚Éƒvƒƒbƒg(”–“§–¾‚ÌŠDF)
               grey = 169 / 255;
               plot(Ptrig3.x,Ptrig3.plotData_sel{d,1}(m,:),'Color',[grey,grey,grey],'LineWidth',LineW);
               %«•½‹Ï‚ðƒvƒƒbƒg(‚±‚ê‚Í•‚Å‚¢‚¢(ok))
               if d == S(2)
                   plot(Ptrig3.x,Ptrig3.AVE{m},'k','LineWidth',LineW);
                   %«ƒ^ƒCƒ~ƒ“ƒO‚Ìü‚ðˆø‚­(•F)(ok)
%                    plot([0 0],[0 160],'-k','LineWidth',LineW);
                   xline(0,'k','LineWidth',LineW)
               end
           elseif restrict_disp == 0
               switch pColor
                 case 'C'
        %              plot(Ptrig2.x,Ptrig2.plotData_sel{d,1}(m,:),'Color',c(d,:),'LineWidth',LineW);
                     plot(Ptrig3.x,Ptrig3.plotData_sel{d,1}(m,:),'Color',Csp(find(PostDays==AllDaysN(d)),:),'LineWidth',LineW);
                 case 'K'
                     plot(Ptrig3.x,Ptrig3.plotData_sel{d,1}(m,:),'k','LineWidth',LineW);
               end
               xline(0,'color','r','LineWidth',LineW)
           end
    %        plot([100 100],[0 160],'-r','LineWidth',LineW);
    %        title([EMGs{m,1} Allfiles{1,d}],'FontSize',fontS);
       end
    %    plot([0 0],[0 160],'-r');
    %    plot([100 100],[0 160],'-r');
       hold off
       if nomalizeAmp == 1
          ylim([0 1]);
       else
          ylim([0 YL]);
       end
    %    xlim([-D.Range2(1) D.Range2(2)]);
       xlim(plotWindow3)
    %    title(EMGs{m,1},'FontSize',fontS);
       if save_fig == 1
           xlabel('task range [%]')
              ylabel('coefficient')
              a = gca;
              a.FontSize = 20;
              a.FontWeight = 'bold';
              a.FontName = 'Arial';
              if restrict_disp == 1
                   restrict_save_dir = 'fig3_data';
                   mkdir(restrict_save_dir)
                   saveas(gcf,[restrict_save_dir '/' Tar sprintf('%d',m) '_' Allfiles{1} 'to' Allfiles{end} '_Trig3_' sprintf('%d',S(end)) '.fig']);
                   saveas(gcf, [restrict_save_dir '/' Tar sprintf('%d',m) '_' Allfiles{1} 'to' Allfiles{end} '_Trig3_' sprintf('%d',S(end)) '.png']);
              else 
                   saveas(gcf,[Tar sprintf('%d',m) '_' Allfiles{1} 'to' Allfiles{end} '_Trig3_' sprintf('%d',S(end)) '.fig']);
                   saveas(gcf,[Tar sprintf('%d',m) '_' Allfiles{1} 'to' Allfiles{end} '_Trig3_' sprintf('%d',S(end)) '.png']);
              end
           
    % %        saveas(gcf,[EMGs{m,1} '_' Allfiles{1} 'to' Allfiles{end} '_Trig2_' sprintf('%d',S(end)) '.epsc']);
    %           saveas(gcf,[EMGs{m,1} '_' Allfiles{1} 'to' Allfiles{end} '_Trig2_' sprintf('%d',S(end)) '.png']);
    %        saveas(gcf,[EMGs{m,1} '_' Allfiles{1} 'to' Allfiles{end} '_Trig2_' sprintf('%d',S(end)) '.fig']);
       end
       if pColor=='K'
          figure(FigTrigSD);
          sd = Ptrig3.SD{m};
          y = Ptrig3.AVE{m};
          xconf = [Ptrig3.x Ptrig3.x(end:-1:1)];
          yconf = [y+sd y(end:-1:1)-sd(end:-1:1)];
          switch EachFigPlot
             case 'on'
                FsubS{m,3} = figure('Position',[1200 720 600 400]);
             case 'off'
                fsd = subplot(subN,4,4*(m-1)+3);
                fsd.FontSize = 5;
          end
          hold on;
          fi = fill(xconf,yconf,'k');
          fi.FaceColor = [0.8 0.8 1];       % make the filled area pink
          fi.EdgeColor = 'none';            % remove the line around the filled area
          plot(Ptrig3.x,y,'k','LineWidth',LineW);
    %       findpeaks(y);
          xline(0,'color','r','LineWidth',LineW)
%           plot([100 100],[0 160],'-r','LineWidth',LineW);
          title(['tirg3 Synergy' sprintf('%d',m)],'FontName', 'Arial','FontWeight', 'bold')
          hold off;
          if nomalizeAmp == 1
             ylim([0 1]);
          else
             ylim([0 YL]);
          end
          xlim(plotWindow3); 
          if save_fig_SD == 1
              xlabel('task range [%]')
              ylabel('coefficient')
              a = gca;
              a.FontSize = 20;
              a.FontWeight = 'bold';
              a.FontName = 'Arial';
              saveas(gcf,[Tar sprintf('%d',m) '_' Allfiles{1} 'to' Allfiles{end} '_Trig3_' sprintf('%d',S(end)) '_SD.fig']);
              saveas(gcf,[Tar sprintf('%d',m) '_' Allfiles{1} 'to' Allfiles{end} '_Trig3_' sprintf('%d',S(end)) '_SD.png']);
          end
          figure(FigTrigAll);
       end
    end
    %save data
    cd ../
    save_dir = ['temporal_synergy_data/' synergy_combination];
    if not(exist(save_dir))
        mkdir(save_dir)
    end
    if pColor == 'K'
        save([save_dir '/pre(' num2str(length(AllDays)) 'days)-data.mat'],'Ptrig3','plotWindow3')
    elseif pColor == 'C'
        save([save_dir '/post(' num2str(length(AllDays)) 'days)-data.mat'],'Ptrig3','plotWindow3')
    end
    cd([Allfiles{1} 'to' Allfiles{end} '_' num2str(length(AllDays))])
    % TRIG4
    for m = 1:Sk(2)%EMG_num loop 
       switch EachFigPlot
          case 'on'
             Fsub{m,4} = figure('Position',[0 720 600 400]);
             switch Tar
                 case 'EMG'
                     title(['tirg4 ' EMGs{m,1}],'FontName', 'Arial','FontWeight', 'bold')
                 case 'Synergy'
                     title(['tirg4 Synergy' sprintf('%d',m)],'FontName', 'Arial','FontWeight', 'bold')
                 case 'Synfixed'
                     title(['tirg4 Synergy' sprintf('%d',m)],'FontName', 'Arial','FontWeight', 'bold')
             end
          case 'off'
             f = subplot(subN,4,4*(m-1)+4);
             f.FontSize = 5;
       end
       hold on
       c = jet(S(2));
    %    c = cool(S(2));
       for d = 1:S(2)%file=num loop
    %     plot(Pall.x,Pall.plotData_sel{d,1}(m,:),'Color',c(find(PostFiles{1,:}==Allfiles(d)),:),'LineWidth',LineW);
          switch pColor
             case 'C'
                 try
                     plot(Pall.x,cell2mat(Pall.plotData_sel{d,1}(m,:)),'Color',Csp(find(PostDays==AllDaysN(d)),:),'LineWidth',LineW);
                 catch
                     plot(Pall.x,Pall.plotData_sel{d,1}(m,:),'Color',Csp(find(PostDays==AllDaysN(d)),:),'LineWidth',LineW);
                 end
             case 'K'
                 try
                     plot(Pall.x,cell2mat(Pall.plotData_sel{d,1}(m,:)),'k','LineWidth',LineW);
                 catch
                     plot(Pall.x,Pall.plotData_sel{d,1}(m,:),'k','LineWidth',LineW);
                 end
          end
           xline(100,'color','r','LineWidth',LineW)
%            plot([100 100],[0 160],'-r','LineWidth',LineW);
    %        title([EMGs{m,1} Allfiles{1,d}],'FontSize',fontS);
       end
    %    xline(0,'color','r','LineWidth',LineW)
    %    plot([100 100],[0 160],'-r','LineWidth',LineW);
       hold off
       if nomalizeAmp == 1
          ylim([0 1]);
       else
          ylim([0 YL]);
       end
       xlim(plotWindow4);
    %    title(EMGs{m,1},'FontSize',fontS);
       if save_fig == 1
           xlabel('task range [%]')
              ylabel('coefficient')
              a = gca;
              a.FontSize = 20;
              a.FontWeight = 'bold';
              a.FontName = 'Arial';
              saveas(gcf,[Tar sprintf('%d',m) '_' Allfiles{1} 'to' Allfiles{end} '_Trig4_' sprintf('%d',S(end)) '.fig']);
              saveas(gcf,[Tar sprintf('%d',m) '_' Allfiles{1} 'to' Allfiles{end} '_Trig4_' sprintf('%d',S(end)) '.png']);
    %        saveas(gcf,[EMGs{m,1} '_' Allfiles{1} 'to' Allfiles{end} '_' sprintf('%d',S(end)) '.epsc']);
    %          saveas(gcf,[EMGs{m,1} '_' Allfiles{1} 'to' Allfiles{end} '_' sprintf('%d',S(end)) '.png']);
    %        saveas(gcf,[EMGs{m,1} '_' Allfiles{1} 'to' Allfiles{end} '_' sprintf('%d',S(end)) '.fig']);
       end
       if pColor=='K'
          figure(FigTrigSD);
          sd = Pall.SD{m};
          y = Pall.AVE{m};
          xconf = [Pall.x Pall.x(end:-1:1)];
          yconf = [y+sd y(end:-1:1)-sd(end:-1:1)];
          switch EachFigPlot
             case 'on'
                FsubS{m,4} = figure('Position',[0 720 600 400]);
             case 'off'
                fsd = subplot(subN,4,4*(m-1)+4);
                fsd.FontSize = 5;
          end
          hold on;
          fi = fill(xconf,yconf,'k');
          fi.FaceColor = [0.8 0.8 1];       % make the filled area pink
          fi.EdgeColor = 'none';            % remove the line around the filled area
          plot(Pall.x,y,'k','LineWidth',LineW);
          xline(100,'color','r','LineWidth',LineW)
%           plot([100 100],[0 160],'-r','LineWidth',LineW);
          title(['tirg4 Synergy' sprintf('%d',m)],'FontName', 'Arial','FontWeight', 'bold')
          hold off;
          if nomalizeAmp == 1
             ylim([0 1]);
          else
             ylim([0 YL]);
          end
          xlim(plotWindow4); 
          if save_fig_SD == 1
              xlabel('task range [%]')
              ylabel('coefficient')
              a = gca;
              a.FontSize = 20;
              a.FontWeight = 'bold';
              a.FontName = 'Arial';
              saveas(gcf,[Tar sprintf('%d',m) '_' Allfiles{1} 'to' Allfiles{end} '_Trig4_' sprintf('%d',S(end)) '_SD.fig']);
              saveas(gcf,[Tar sprintf('%d',m) '_' Allfiles{1} 'to' Allfiles{end} '_Trig4_' sprintf('%d',S(end)) '_SD.png']);
          end
          figure(FigTrigAll);
       end
    end
    % f2.FontSize = 5;
     save_Allfig = 0;
    if save_Allfig == 1
        SaveFig(f1,['PreAll_' Allfiles{1} 'to' Allfiles{end} '_' sprintf('%d',S(end))])
        SaveFig(f2,['PreEach_' Allfiles{1} 'to' Allfiles{end} '_' sprintf('%d',S(end))])
    %    saveas(f1,['CrossTalk_' Allfiles{1} 'to' Allfiles{end} '_' sprintf('%d',S(end)) '.epsc']);
    %    saveas(f1,['CrossTalk_' Allfiles{1} 'to' Allfiles{end} '_' sprintf('%d',S(end)) '.png']);
    %    saveas(f1,['CrossTalk_' Allfiles{1} 'to' Allfiles{end} '_' sprintf('%d',S(end)) '.fig']);
    %    saveas(f2,['CrossTalk3rd_' Allfiles{1} 'to' Allfiles{end} '_' sprintf('%d',S(end)) '.epsc']);
    %    saveas(f2,['CrossTalk3rd_' Allfiles{1} 'to' Allfiles{end} '_' sprintf('%d',S(end)) '.png']);
    %    saveas(f2,['CrossTalk3rd_' Allfiles{1} 'to' Allfiles{end} '_' sprintf('%d',S(end)) '.fig']);
    end
    save_fingerFigs = 0;
    if save_fingerFigs == 1
        cd('EachPlot')
        for tt = 1:4
            for mm = 1:Sk(2)
                SaveFig(Fsub{mm,tt},['PlotEachAlignedOnTask_' EMGs{mm,1} 'Aligned_' sprintf('%d',tt)])
            end
        end
        cd ../
    end
end
cd ../../../
if save_xcorr_data == 1
    save_fold = 'easyData/P-DATA(TTakei-filter)/'; %ƒtƒ@ƒCƒ‹‚ðƒZ[ƒu‚·‚éêŠ
    AllTAVE = Pall.AllT_AVE;
    plotData_sel = Pall.plotData_sel;
    save([save_fold 'AllDataforXcorr_' num2str(length(Allfiles)) '_' num2str(subN) 'syn.mat'],'Allfiles','AllTAVE','realname','taskRange','plotData_sel')
    save([save_fold 'DataSetforEachXcorr_' num2str(length(Allfiles)) '_' num2str(subN) 'syn.mat'],'Allfiles','plotWindow1','plotWindow2','plotWindow3','plotWindow4','realname','TrigData_Each')
end
close all
% end
%% Get each alighned timing 
% function [] = getTiming(Timing,Tp,i)
% Timing.obj1s(i,:) = mean(Tp - Tp(:,2));
% Timing.obj1s(i,:) = mean(Tp - Tp(:,3));
% end

% function [] = nomalizeData(Allfiles_S,S,dataName)
% for j = 1:S(2)%file=num loop
%      S = load(Allfiles_S{j},dataName);
%     Sk = size(S.alignedDataAVE);
%     plotData = zeros(Sk(2),AllT_AVE);
%     if AllTlist(j,1) == AllT_AVE
%         for k = 1:Sk(2)%EMG_num loop 
%             sec(1,1) = sec(1,1)+1;
%             plotData(k,:) = alignedDataAVE{1,k};
%         end
%     elseif AllTlist(j,1)<AllT_AVE 
%         for k = 1:Sk(2)%EMG_num loop 
%             sec(2,1) = sec(2,1)+1;
%             plotData(k,:) = interpft(alignedDataAVE{1,k},AllT_AVE);
%         end
%     else
%         for k = 1:Sk(2)%EMG_num loop 
%             sec(3,1) = sec(3,1)+1;
%             plotData(k,:) = resample(alignedDataAVE{1,k},AllT_AVE,AllTlist(j,1));
%         end
%     end
%     
%     plotData_sel{j,1} = plotData;
% end
% end