XLim    = [-10 60];
XTick   = [0:20:80];
YLim    = [-0.1 0.12];

h   = subplot(4,1,1);
plot(XData,aYData1,'k','LineWidth',1)
set(h,'LineWidth',1,...
    'TickDir','out',...
    'XLim',XLim,...
    'XTick',XTick,...
    'YLim',YLim)

h   = subplot(4,1,2);
plot(XData,aYData2,'k','LineWidth',1)
set(h,'LineWidth',1,...
    'TickDir','out',...
    'XLim',XLim,...
    'XTick',XTick,...
    'YLim',YLim)

h   = subplot(4,1,3);
plot(XData,aYData3,'k','LineWidth',1)
set(h,'LineWidth',1,...
    'TickDir','out',...
    'XLim',XLim,...
    'XTick',XTick,...
    'YLim',YLim)

h   = subplot(4,1,4);
plot(XData,aYData4,'k','LineWidth',1)
set(h,'LineWidth',1,...
    'TickDir','out',...
    'XLim',XLim,...
    'XTick',XTick,...
    'YLim',YLim)
