function count  =correctphase
count   = 0;
outfile = 'C:\data\cohband\all2.xls';
% fid     = fopen(outfile,'a')
 
dirs    ={'C:\data\cohband\all\AobaT00101',...
    'C:\data\cohband\all\AobaT00201',...
    'C:\data\cohband\all\AobaT00203',...
    'C:\data\cohband\all\AobaT00301',...
    'C:\data\cohband\all\AobaT00302',...
    'C:\data\cohband\all\AobaT00305',...
    'C:\data\cohband\all\AobaT00306',...
    'C:\data\cohband\all\AobaT00402',...
    'C:\data\cohband\all\AobaT00502',...
    'C:\data\cohband\all\AobaT00503',...
    'C:\data\cohband\all\AobaT00602',...
    'C:\data\cohband\all\AobaT00603',...
    'C:\data\cohband\all\AobaT00608',...
    'C:\data\cohband\all\AobaT00702',...
    'C:\data\cohband\all\AobaT00801',...
    'C:\data\cohband\all\AobaT00805',...
    'C:\data\cohband\all\AobaT00808',...
    'C:\data\cohband\all\AobaT00812',...
    'C:\data\cohband\all\AobaT00902',...
    'C:\data\cohband\all\AobaT00903',...
    'C:\data\cohband\all\AobaT00907',...
    'C:\data\cohband\all\AobaT00914',...
    'C:\data\cohband\all\AobaT01101',...
    'C:\data\cohband\all\AobaT01106',...
    'C:\data\cohband\all\AobaT01108',...
    'C:\data\cohband\all\AobaT01112',...
    'C:\data\cohband\all\AobaT01114',...
    'C:\data\cohband\all\AobaT01115',...
    'C:\data\cohband\all\AobaT01201',...
    'C:\data\cohband\all\AobaT01202',...
    'C:\data\cohband\all\AobaT01204',...
    'C:\data\cohband\all\AobaT01301',...
    'C:\data\cohband\all\AobaT01307',...
    'C:\data\cohband\all\AobaT01310',...
    'C:\data\cohband\all\AobaT01313',...
    'C:\data\cohband\all\AobaT01401',...
    'C:\data\cohband\all\AobaT01609',...
    'C:\data\cohband\all\AobaT01702',...
    'C:\data\cohband\all\AobaT01801',...
    'C:\data\cohband\all\AobaT01901',...
    'C:\data\cohband\all\AobaT01905',...
    'C:\data\cohband\all\AobaT01907',...
    'C:\data\cohband\all\AobaT01911',...
    'C:\data\cohband\all\AobaT02103',...
    'C:\data\cohband\all\AobaT02202',...
    'C:\data\cohband\all\AobaT02401',...
    'C:\data\cohband\all\AobaT02403',...
    'C:\data\cohband\all\AobaT02405',...
    'C:\data\cohband\all\AobaT02407',...
    'C:\data\cohband\all\AobaT02501',...
    'C:\data\cohband\all\AobaT02502',...
    'C:\data\cohband\all\AobaT02503',...
    'C:\data\cohband\all\T01305',...
    'C:\data\cohband\all\T01307',...
    'C:\data\cohband\all\T01308',...
    'C:\data\cohband\all\T01309',...
    'C:\data\cohband\all\T02102',...
    'C:\data\cohband\all\T02103',...
    'C:\data\cohband\all\T02105',...
    'C:\data\cohband\all\T02106'};
% dirs    ={'C:\data\cohband\Typical\AobaT00101',...
%     'C:\data\cohband\Typical\AobaT00203',...
%     'C:\data\cohband\Typical\AobaT00301',...
%     'C:\data\cohband\Typical\AobaT00302',...
%     'C:\data\cohband\Typical\AobaT00305',...
%     'C:\data\cohband\Typical\AobaT00306',...
%     'C:\data\cohband\Typical\AobaT00402',...
%     'C:\data\cohband\Typical\AobaT00503',...
%     'C:\data\cohband\Typical\AobaT00602',...
%     'C:\data\cohband\Typical\AobaT00603',...
%     'C:\data\cohband\Typical\AobaT00702',...
%     'C:\data\cohband\Typical\AobaT00808',...
%     'C:\data\cohband\Typical\AobaT00907',...
%     'C:\data\cohband\Typical\AobaT00914',...
%     'C:\data\cohband\Typical\AobaT01106',...
%     'C:\data\cohband\Typical\AobaT01108',...
%     'C:\data\cohband\Typical\AobaT01114',...
%     'C:\data\cohband\Typical\AobaT01115',...
%     'C:\data\cohband\Typical\AobaT01204',...
%     'C:\data\cohband\Typical\AobaT01307',...
%     'C:\data\cohband\Typical\AobaT01310',...
%     'C:\data\cohband\Typical\AobaT01313',...
%     'C:\data\cohband\Typical\AobaT02403',...
%     'C:\data\cohband\Typical\AobaT02407',...
%     'C:\data\cohband\Typical\AobaT02502',...
%     'C:\data\cohband\Typical\AobaT02503',...
%     'C:\data\cohband\Typical\T01309',...
%     'C:\data\cohband\Typical\T02102',...
%     'C:\data\cohband\Typical\T02103',...
%     'C:\data\cohband\Typical\T02105',...
%     'C:\data\cohband\Typical\T02106'};
length(dirs)
for jj=1:length(dirs)

%     parentdir   = uigetdir;
    parentdir   =dirs{jj};
    
    w           = what(parentdir);
    disp(['[+] ',parentdir])
    filename    = cell(1);
    for ii=1:length(w.mat)
        filename{ii}    = [parentdir,'\',w.mat{ii}];
        disp(['  L__',num2str(ii),':  ',filename{ii}])
    end

    % [S,filename] = topen;
    if(class(filename)=='cell')
        nloop = length(filename);
    else
        nloop = 1;
    end


    for ii=1:nloop
        if(class(filename)=='cell')
            matname = filename{ii};
        else
            matname = filename;
        end
        figname     = [matname(1:(strfind(matname,'.mat')-1)),'.fig'];
    %     disp(num2str(ii))
        
     
    
        load(matname)
%         x   = f(:,1);
%         c   = f(:,4);
%         p   = f(:,5);
%     %     pp  = p/pi;     % pi -1<pp<1
%         lim = cl.ch_c95;
%         sixtyonehundred = ((x > 63) & (x <= 100));
%         sixtyonehundredchk = c(sixtyonehundred) > lim;
%         if(any(sixtyonehundredchk))
%             opt.sixtyonehundred  = 1;
%         else
%             opt.sixtyonehundred  = 0;
%             count   = count+1;
%         end
        opt.typical = 0;
        save(matname,'f','cl','opt')

% %         load(matname)
%         if(opt.hum  == 0);
%             if(~isempty(strfind(matname,'Aoba')))
%                 animalname  ='Aoba';
%             else
%                 animalname  ='Uma';
%             end
%             sitename    = matname((strfind(matname,'T')):(strfind(matname,'T')+5));
%             EMGname     = matname((strfind(matname,'__'))+2:(strfind(matname,'-rect'))-1);
%             count   = count+1;
%             fprintf(fid,'%d\t%d\t%s\t%s\t%s\t%d\n',count,jj,animalname,sitename,EMGname,opt.sixtyonehundred);
%         end
% %         

        
%         open(figname)
%         
%         sig=c>lim;
%         h   =subplot(4,1,3);
%         set(h,'Nextplot','replacechildren')
%         hl  =plot(h,[x(sig);x(sig);x(sig)],[p(sig)-2*pi;p(sig);p(sig)+2*pi],'ob','MarkerFaceColor','b','MarkerSize',3);
%         set(hl,'Tag','significant')
%         set(h,'Nextplot','add')
%         hl  =plot(h,[x(~sig);x(~sig);x(~sig)],[p(~sig)-2*pi;p(~sig);p(~sig)+2*pi],'ob','MarkerFaceColor','w','MarkerSize',3);
%         set(hl,'Tag','nonsignificant')
%         %     plot(h,x(~sig),p(~sig),'ob','MarkerFaceColor','w','MarkerSize',3)
%     %     plot(h,x(sig),p(sig)-2,'ob','MarkerFaceColor','b','MarkerSize',3)
%     %     plot(h,x(~sig),p(~sig)-2,'ob','MarkerFaceColor','w','MarkerSize',3)
%         set(h,'Nextplot','replace')
%         set(h,'xlim',[5 150],...
%             'ylim',[-2*pi 2*pi],...
%             'yTickMode','manual',...
%             'yTick',[-3*pi -2*pi -pi 0 pi 2*pi 3*pi],...
%             'yTickLabel',{'-3pi' '-2pi' '-pi' '0' 'pi' '2pi' '3pi'})
%         ylabel(h,'Phase')
% 
%         set(gcf,'Position',[320 60 640 900]);
%         
% 
%         f=uicontextmenu;
%         uimenu(f,'Label','uiregress','callback','uiregress([])')
%         
%         h   =findobj(gcf,'Type','axes');
%         set(h,'xlim',[5 100],...
%         'UIContextMenu',f);
% 
%         saveas(gcf,figname,'fig')
%         close(gcf)

    end
%     cd(parentdir)
end
% fclose(fid)