NB	=   load('L:\tkitom\data\wcohclssig\071106(combine)(-AobaT003)\T02101_Non-filtered-subsample(uV)__FDI-subsample(uV).mat');
BB	=   load('L:\tkitom\data\wcohclssig\071106(combine)(-AobaT003)\AobaT00203_Non-filtered-subsample(uV)__FDPr-subsample(uV).mat');


% trange	= [57 :157];    % REST -0.8 - - 0.4sec
Grange	= [257:357];        % Grip0 - 0.4 sec
Hrange	= [507:607];        % HOLD 1.0 - 1.4 sec 


% 
% FOI     = [8:32];   % 10-40 Hz
% FOI     = [8:44,52:76];   % 10-55 65-95 Hz
FOING     = [4:28];   % 5-35 Hz                 NG
FOINH     = [19:23];   % 5-35 Hz                 NH
FOIBG     = [4:43,53:76];   % 5-55 65-95 Hz    BG
FOIBH     = [11:43,53:74];   % 13.75-55 65-92.5 Hz      BH

% FOI     = [4:11];   % 5-12.5 Hz    BG alpha
% FOI     = [12:43,53:76];   % 16.25-55 65-95Hz    BG non-alpha

FOImaskNG = logical(zeros(80,1));
FOImaskNG(FOING)    = ones(length(FOING),1); 

FOImaskNH = logical(zeros(80,1));
FOImaskNH(FOINH)    = ones(length(FOINH),1); 

FOImaskBG = logical(zeros(80,1));
FOImaskBG(FOIBG)    = ones(length(FOIBG),1); 

FOImaskBH = logical(zeros(80,1));
FOImaskBH(FOIBH)    = ones(length(FOIBH),1); 

TLim    = [-1 1.5];
TTick   = [-1:0.5:1.5];
FLim    = [0 100];
FTick   = [0:20:100];


% trange	= [5:632];

freq    = NB.freq;
t       = NB.t;



% NB
fig     = figure;
    
cont    = uicontextmenu('Parent',fig);
uimenu(cont,'Label','uiregress','callback','uiregress2(''sig'')')


h   = subplot(2,2,[1,2]);
H   =pcolor(h,t,freq,NB.cxy);shading flat
set(H,'EdgeColor','none')
set(h,'Box','On',...
    'CLim',[NB.cl.ch_c95,0.15],...
    'Clipping','On',...
    'LineWidth',1,...
    'TickDir','Out',...
    'TickLength',[0.025 0.05],...
    'XLim',TLim,...
    'XTick',TTick,...
    'YLim',FLim,...
    'YTick',FTick);
hh   = colorbar;
set(hh,'Box','On',...
    'LineWidth',1,...
    'TickDir','Out',...
    'TickLength',[0.025 0.05],...
    'YTick',[0.05:0.05:0.15]);

h   = subplot(2,2,3);
phi = nanmask(NB.phi,NB.csig);
phi = phi(:,Grange);
meanphi = nanmean(optunwrap(phi,-pi),2);
stdphi  = nanstd(optunwrap(phi,-pi),0,2);
meanphi = nanmask(meanphi,FOImaskNG);
stdphi  = nanmask(stdphi,FOImaskNG);
% terrorbar(h,[freq';freq';freq'],[meanphi-2*pi;meanphi;meanphi+2*pi],[stdphi;stdphi;stdphi] ,'ok','MarkerEdgeColor','none','MarkerFaceColor','k','MarkerSize',4,'Tag','sig');
plot(h,[freq';freq';freq'],[meanphi-2*pi;meanphi;meanphi+2*pi],'ok','MarkerEdgeColor','none','MarkerFaceColor','k','MarkerSize',4,'Tag','sig');
set(h,'Box','On',...
    'Clipping','On',...
    'LineWidth',1,...
    'TickDir','Out',...
    'TickLength',[0.025 0.05],...
    'UIContextMenu',cont,...
    'XLim',FLim,...
    'XTick',FTick,...
    'YLim',[-2*pi 2*pi],...
    'YTickMode','manual',...
    'YTick',[-3*pi -2*pi -pi 0 pi 2*pi 3*pi],...
    'YTickLabel',{'-3pi' '-2pi' '-pi' '0' 'pi' '2pi' '3pi'});

h   = subplot(2,2,4);
phi = nanmask(NB.phi,NB.csig);
phi = phi(:,Hrange);
meanphi = nanmean(optunwrap(phi,-pi),2);
stdphi  = nanstd(optunwrap(phi,-pi),0,2);
meanphi = nanmask(meanphi,FOImaskNH);
stdphi  = nanmask(stdphi,FOImaskNH);
% terrorbar(h,[freq';freq';freq'],[meanphi-2*pi;meanphi;meanphi+2*pi],[stdphi;stdphi;stdphi] ,'ok','MarkerEdgeColor','none','MarkerFaceColor','k','MarkerSize',4,'Tag','sig');
plot(h,[freq';freq';freq'],[meanphi-2*pi;meanphi;meanphi+2*pi],'ok','MarkerEdgeColor','none','MarkerFaceColor','k','MarkerSize',4,'Tag','sig');
set(h,'Box','On',...
    'Clipping','On',...
    'LineWidth',1,...
    'TickDir','Out',...
    'TickLength',[0.025 0.05],...
    'UIContextMenu',cont,...
    'XLim',FLim,...
    'XTick',FTick,...
    'YLim',[-2*pi 2*pi],...
    'YTickMode','manual',...
    'YTick',[-3*pi -2*pi -pi 0 pi 2*pi 3*pi],...
    'YTickLabel',{'-3pi' '-2pi' '-pi' '0' 'pi' '2pi' '3pi'});


colormap(tmap2)







% BB
fig     = figure;
    
cont    = uicontextmenu('Parent',fig);
uimenu(cont,'Label','uiregress','callback','uiregress2(''sig'')')

h   =subplot(2,2,[1,2]);
H   =pcolor(h,t,freq,BB.cxy);shading flat
set(H,'EdgeColor','none')
set(h,'Box','On',...
    'CLim',[BB.cl.ch_c95,0.15],...
    'Clipping','On',...
    'LineWidth',1,...
    'TickDir','Out',...
    'TickLength',[0.025 0.05],...
    'XLim',TLim,...
    'XTick',TTick,...
    'YLim',FLim,...
    'YTick',FTick);
hh   = colorbar;
set(hh,'Box','On',...
    'LineWidth',1,...
    'TickDir','Out',...
    'TickLength',[0.025 0.05],...
    'YTick',[0.05:0.05:0.15]);

h   = subplot(2,2,3);
phi = nanmask(BB.phi,BB.csig);
phi = phi(:,Grange);
meanphi = nanmean(optunwrap(phi,-pi),2);
stdphi  = nanstd(optunwrap(phi,-pi),0,2);
meanphi = nanmask(meanphi,FOImaskBG);
stdphi  = nanmask(stdphi,FOImaskBG);
% terrorbar(h,[freq';freq';freq'],[meanphi-2*pi;meanphi;meanphi+2*pi],[stdphi;stdphi;stdphi] ,'ok','MarkerEdgeColor','none','MarkerFaceColor','k','MarkerSize',4,'Tag','sig');
plot(h,[freq';freq';freq'],[meanphi-2*pi;meanphi;meanphi+2*pi],'ok','MarkerEdgeColor','none','MarkerFaceColor','k','MarkerSize',4,'Tag','sig');
set(h,'Box','On',...
    'Clipping','On',...
    'LineWidth',1,...
    'TickDir','Out',...
    'TickLength',[0.025 0.05],...
    'UIContextMenu',cont,...
    'XLim',FLim,...
    'XTick',FTick,...
    'YLim',[-2*pi 2*pi],...
    'YTickMode','manual',...
    'YTick',[-3*pi -2*pi -pi 0 pi 2*pi 3*pi],...
    'YTickLabel',{'-3pi' '-2pi' '-pi' '0' 'pi' '2pi' '3pi'});


h   = subplot(2,2,4);
phi = nanmask(BB.phi,BB.csig);
phi = phi(:,Hrange);
meanphi = nanmean(optunwrap(phi,-pi),2);
stdphi  = nanstd(optunwrap(phi,-pi),0,2);
meanphi = nanmask(meanphi,FOImaskBH);
stdphi  = nanmask(stdphi,FOImaskBH);
% terrorbar(h,[freq';freq';freq'],[meanphi-2*pi;meanphi;meanphi+2*pi],[stdphi;stdphi;stdphi] ,'ok','MarkerEdgeColor','none','MarkerFaceColor','k','MarkerSize',4,'Tag','sig');
plot(h,[freq';freq';freq'],[meanphi-2*pi;meanphi;meanphi+2*pi],'ok','MarkerEdgeColor','none','MarkerFaceColor','k','MarkerSize',4,'Tag','sig');
set(h,'Box','On',...
    'Clipping','On',...
    'LineWidth',1,...
    'TickDir','Out',...
    'TickLength',[0.025 0.05],...
    'UIContextMenu',cont,...
    'XLim',FLim,...
    'XTick',FTick,...
    'YLim',[-2*pi 2*pi],...
    'YTickMode','manual',...
    'YTick',[-3*pi -2*pi -pi 0 pi 2*pi 3*pi],...
    'YTickLabel',{'-3pi' '-2pi' '-pi' '0' 'pi' '2pi' '3pi'});


colormap(tmap2)

