load('phase regress 071119');

XLim    = [-120 120];
XTick   = [-100 :25:100];
YLim    = [0 12];
YTick   = [0:2:12];


figure

h   =subplot(2,2,1);
bar(X,NBG,1,'FaceColor','none','LineWidth',1)
set(h,'Box','on',...
    'LineWidth',1,...
    'TickDir','out',...
    'TickLength',[0.025 0.05],...
    'XLim',XLim,...
    'XTick',XTick,...
    'YLim',YLim,...
    'YTick',YTick);

h   =subplot(2,2,3);
bar(X,NBH,1,'FaceColor','none','LineWidth',1)
set(h,'Box','on',...
    'LineWidth',1,...
    'TickDir','out',...
    'TickLength',[0.025 0.05],...
    'XLim',XLim,...
    'XTick',XTick,...
    'YLim',YLim,...
    'YTick',YTick);

h   =subplot(2,2,2);
bar(X,BBG,1,'FaceColor','none','LineWidth',1)
set(h,'Box','on',...
    'LineWidth',1,...
    'TickDir','out',...
    'TickLength',[0.025 0.05],...
    'XLim',XLim,...
    'XTick',XTick,...
    'YLim',YLim,...
    'YTick',YTick);

h   =subplot(2,2,4);
bar(X,BBH,1,'FaceColor','none','LineWidth',1)
set(h,'Box','on',...
    'LineWidth',1,...
    'TickDir','out',...
    'TickLength',[0.025 0.05],...
    'XLim',XLim,...
    'XTick',XTick,...
    'YLim',YLim,...
    'YTick',YTick);
