function eito_cortex_cordinate


fig    = figure;
h    = subplot(1,1,1,'Parent',fig);


% [0,0,0]
plot3(0,0,0,'+b','Parent',h)
hold(h,'on');

% rM1 hand area
plot3(17,12,35,'*r','Parent',h)


% reference points 
plot3(18.1,-1,41.4,'ob','Parent',h)    % A
plot3(9.7,13.6,44.1,'ob','Parent',h)   % B
plot3(26.5,15.2,33.2,'ob','Parent',h)  % C

% configure axis

xl  = xlabel('M-L');
yl  = ylabel('C-R');
zl  = zlabel('V-D');


axis(h,'equal');

set(h,'XDir','normal',...
    'XGrid','on',...
    'XLabel',xl,...
    'XLim',[0 30],...
    'XLimMode','manual',...
    'XMinorGrid','off',...
    'XMinorTick','off',...
    'XScale','linear',...
    'XTick',[-10:10:50],...
    'XTickLabelMode','auto',...
    'XTickMode','auto',...
    'YDir','normal',...
    'YGrid','on',...
    'YLabel',yl,...
    'YLim',[-10 30],...
    'YLimMode','manual',...
    'YMinorGrid','off',...
    'YMinorTick','off',...
    'YScale','linear',...
    'YTick',[-10:10:50],...
    'YTickLabelMode','auto',...
    'YTickMode','auto',...
    'ZDir','normal',...
    'ZGrid','on',...
    'ZLabel',zl,...
    'ZLim',[0 50],...
    'ZLimMode','manual',...
    'ZMinorGrid','off',...
    'ZMinorTick','off',...
    'ZScale','linear',...
    'ZTick',[-10:10:50],...
    'ZTickLabelMode','auto',...
    'ZTickMode','auto');


fig    =figure;
h       = subplot(1,1,1,'Parent',fig);
%           ML  RC  Depth   Threshold
finger  = [0,   -8.5,   2007,   NaN;...
    0,  -8.5,   3000,   NaN;...
    0,  -8.5,   5000,   NaN;...
    0,  -4.5,   2250,   5;...
    0,  -4.5,   2750,   4;...
    0,  -4.5,   3250,   6;...
    0,  -4.5,   3750,   14;...
    0,  -4.5,   4250,   13;...
    0,  -4.5,   4750,   17;...
    0,  -4.5,   5250,   11;...
    0,  -4.5,   5750,   15;...
    -2, -4.5,   2000,   8;...
    -2, -4.5,   2500,   8;...
    -2, -4.5,   3000,   9;...
    -2, -4.5,   3500,   12;...
    -2, -4.5,   4000,   7;...
    -4, -4.5,   2500,   NaN;...
    -4, -4.5,   3000,   NaN;...
    -4, -4.5,   4000,   6;...
    -4, -4.5,   5000,   26;...
    -6, -4.5,   2000,   NaN;...
    -6, -4.5,   3000,   NaN;...
    -6, -4.5,   4000,   NaN;...
    +4, -4.5,   2500,   NaN;...
    +4, -4.5,   3500,   NaN;...
    0,  -0.5,   3000,   9;...
    0,  -0.5,   4000,   8;...
    0,  +3.5,   3500,   NaN;...
    0,  +3.5,   4500,   NaN;...
    0,  +1.5,   2000,   NaN;...
    0,  +1.5,   3000,   NaN;...
    0,  +1.5,   4000,   NaN;...
    0,  +1.5,   5000,   NaN;...
    -4,  -0.5,   2000,   15;...
    -4,  -0.5,   3000,   25;...
    -4,  -0.5,   4000,   35;...
    -2,  -0.5,   2500,   30;...
    -2,  -0.5,   3500,   10;...
    -2,  -0.5,   4500,   20];


nfinger = size(finger,1);

hold(h,'on');
for ifinger = 1:nfinger
    if(isnan(finger(ifinger,4)))
        msize   = 2;
        mstyle  = 'o';
        mcolor  = 'k';
    elseif(finger(ifinger,4)<=5)
        msize   = 12;
        mstyle  = 'o';
        mcolor  = 'r';
    elseif(finger(ifinger,4)<=10)
        msize   = 10;
        mstyle  = 'o';
        mcolor  = 'r';
        elseif(finger(ifinger,4)<=15)
        msize   = 8;
        mstyle  = 'o';
        mcolor  = 'r';
    elseif(finger(ifinger,4)<=20)
        msize   = 6;
        mstyle  = 'o';
        mcolor  = 'r';
    elseif(finger(ifinger,4)<=25)
        msize   = 4;
        mstyle  = 'o';
        mcolor  = 'k';
    elseif(finger(ifinger,4)<=30)
        msize   = 2;
        mstyle  = 'o';
        mcolor  = 'k';
    else
        msize   = 2;
        mstyle  = 'o';
        mcolor  = 'k';
    end
        
        
    plot3(finger(ifinger,1),finger(ifinger,2),finger(ifinger,3)/-1000,'Marker',mstyle,'MarkerEdgeColor',mcolor,'MarkerFaceColor',mcolor,'Markersize',msize,'Parent',h)
end


% configure axis

xl  = xlabel('M-L');
yl  = ylabel('C-R');
zl  = zlabel('V-D');


axis(h,'equal');

set(h,'XDir','normal',...
    'XGrid','on',...
    'XLabel',xl,...    'XLim',[0 30],...
    'XLimMode','auto',...
    'XMinorGrid','off',...
    'XMinorTick','off',...
    'XScale','linear',...    
    'XTick',[-10:0.5:10],...
    'XTickLabelMode','manual',...
    'XTickMode','auto',...
    'YDir','normal',...
    'YGrid','on',...
    'YLabel',yl,...    'YLim',[-10 30],...
    'YLimMode','auto',...
    'YMinorGrid','off',...
    'YMinorTick','off',...
    'YScale','linear',...    
    'YTick',[-10:0.5:3],...
    'YTickLabelMode','manual',...
    'YTickMode','auto',...
    'ZDir','normal',...
    'ZGrid','on',...
    'ZLabel',zl,...    'ZLim',[0 50],...
    'ZLimMode','auto',...
    'ZMinorGrid','off',...
    'ZMinorTick','off',...
    'ZScale','linear',...    
    'ZTick',[-8:0.5:0],...
    'ZTickLabelMode','manual',...
    'ZTickMode','auto');