function getspike_figure
global gsobj


fig = figure;
set(fig,'Name','GetSpike',...
    'Numbertitle','Off',...
    'Pointer','Arrow',...
    'Position',[3         573        1677         373],...
    'Tag','gsdisplay',...
    'Toolbar','Figure');

h1  = axes('Position',[0.029 0.887 0.901 0.083]);
set(h1,'NextPlot','replacechildren',...
    'Tag','reference',...
    'XTick',[],...
    'XTickMode','Manual',...
    'YTick',[],...
    'YTickMode','Manual');

h2  = axes('Position',[0.029 0.78 0.901 0.083]);
set(h2,'NextPlot','replacechildren',...
    'Tag','spike',...
    'XTick',[],...
    'XTickMode','Manual',...
    'YTick',[],...
    'YTickMode','Manual');

h3  = axes('Position',[0.029 0.324 0.901 0.432]);
set(h3,'Tag','unit');


linkaxes([h1,h2,h3],'x');

gsobj.handles.gsdisplay     = fig;
gsobj.handles.ref           = h1;
gsobj.handles.spike         = h2;
gsobj.handles.unit          = h3;

gsobj.handles.panel      = uipanel('Unit','Normalized',...
    'Position',[0.053 0.029 0.4 0.234]);

uicontrol('Unit','Normalized',...
    'HorizontalAlignment','left',...
    'Parent',gsobj.handles.panel,...
    'Position',[0.028 0.802 0.129 0.188],...
    'String','Path:',...
    'Style','text');
gsobj.handles.pathnametext      = uicontrol('Unit','Normalized',...
    'Parent',gsobj.handles.panel,...
    'Position',[0.171 0.802 0.473 0.188],...
    'String','not selected',...
    'Style','text',...
    'Tag','pathnametext');
gsobj.handles.pathloadbutton    = uicontrol('Unit','Normalized',...
    'Callback','getspike(''pathload'')',...
    'Parent',gsobj.handles.panel,...
    'Position',[0.688 0.802 0.129 0.188],...
    'String','Load',...
    'Style','Pushbutton',...
    'Tag','pathloadbutton');

uicontrol('Unit','Normalized',...
    'HorizontalAlignment','left',...
    'Parent',gsobj.handles.panel,...
    'Position',[0.028 0.604 0.129 0.188],...
    'String','  Unit:',...
    'Style','text');
gsobj.handles.unitnametext      = uicontrol('Unit','Normalized',...
    'Parent',gsobj.handles.panel,...
    'Position',[0.171 0.604 0.473 0.188],...
    'String','not selected',...
    'Style','text',...
    'Tag','unitnametext');
gsobj.handles.unitloadbutton    = uicontrol('Unit','Normalized',...
    'Callback','getspike(''unitload'')',...
    'Parent',gsobj.handles.panel,...
    'Position',[0.688 0.604 0.129 0.188],...
    'String','Load',...
    'Style','Pushbutton',...
    'Tag','unitloadbutton');
gsobj.handles.unitsavebutton   = uicontrol('Unit','Normalized',...
    'Callback','getspike(''unitsave'')',...
    'Parent',gsobj.handles.panel,...
    'Position',[0.838 0.604 0.129 0.188],...
    'String','Save',...
    'Style','Pushbutton',...
    'Tag','unitsavebutton');

uicontrol('Unit','Normalized',...
    'HorizontalAlignment','left',...
    'Parent',gsobj.handles.panel,...
    'Position',[0.028 0.406 0.151 0.188],...
    'String','  Event:',...
    'Style','text');
gsobj.handles.refnametext      = uicontrol('Unit','Normalized',...
    'Parent',gsobj.handles.panel,...
    'Position',[0.171 0.406 0.473 0.188],...
    'String','not selected',...
    'Style','text',...
    'Tag','refnametext');
gsobj.handles.refloadbutton    = uicontrol('Unit','Normalized',...
    'Callback','getspike(''refload'')',...
    'Parent',gsobj.handles.panel,...
    'Position',[0.688 0.406 0.129 0.188],...
    'String','Load',...
    'Style','Pushbutton',...
    'Tag','refloadbutton');
gsobj.handles.refsavebutton   = uicontrol('Unit','Normalized',...
    'Callback','getspike(''refsave'')',...
    'Parent',gsobj.handles.panel,...
    'Position',[0.838 0.406 0.129 0.188],...
    'String','Save',...
    'Style','Pushbutton',...
    'Tag','refsavebutton');

uicontrol('Unit','Normalized',...
    'HorizontalAlignment','left',...
    'Parent',gsobj.handles.panel,...
    'Position',[0.028 0.208 0.129 0.188],...
    'String','  Reference:',...
    'Style','text');
gsobj.handles.msdnametext      = uicontrol('Unit','Normalized',...
    'Parent',gsobj.handles.panel,...
    'Position',[0.171 0.208 0.473 0.188],...
    'String','not selected',...
    'Style','text',...
    'Tag','msdnametext');
gsobj.handles.msdloadbutton    = uicontrol('Unit','Normalized',...
    'Callback','getspike(''msdload'')',...
    'Parent',gsobj.handles.panel,...
    'Position',[0.688 0.208 0.129 0.188],...
    'String','Load',...
    'Style','Pushbutton',...
    'Tag','msdloadbutton');

uicontrol('Unit','Normalized',...
    'HorizontalAlignment','left',...
    'Parent',gsobj.handles.panel,...
    'Position',[0.028 0.01 0.129 0.188],...
    'String','  Force:',...
    'Style','text');
gsobj.handles.tracenametext      = uicontrol('Unit','Normalized',...
    'Parent',gsobj.handles.panel,...
    'Position',[0.171 0.01 0.473 0.188],...
    'String','not selected',...
    'Style','text',...
    'Tag','tracenametext');
gsobj.handles.traceloadbutton    = uicontrol('Unit','Normalized',...
    'Callback','getspike(''traceload'')',...
    'Parent',gsobj.handles.panel,...
    'Position',[0.688 0.01 0.129 0.188],...
    'String','Load',...
    'Style','Pushbutton',...
    'Tag','traceloadbutton');

gsobj.handles.rasterbutton   = uicontrol('Unit','Normalized',...
    'Callback','getspike(''raster_plot'')',...
    'Position',[0.5 0.083 0.072 0.11],...
    'String','Raster',...
    'Style','Pushbutton',...
    'Tag','rasterbutton');

gsobj.handles.wavplaybutton   = uicontrol('Unit','Normalized',...
    'Callback','getspike(''wavplay'')',...
    'Position',[0.596 0.083 0.072 0.11],...
    'String','Play',...
    'Style','Pushbutton',...
    'Tag','wavplaybutton');

gsobj.handles.scopebutton   = uicontrol('Unit','Normalized',...
    'Callback','getspike(''scope'')',...
    'Position',[0.691 0.083 0.072 0.11],...
    'String','Scope',...
    'Style','Pushbutton',...
    'Tag','scopebutton');

gsobj.handles.threshold	= uicontrol('Unit','Normalized',...
    'Callback','getspike(''scope'')',...
    'Position',[0.775 0.083 0.084 0.056],...
    'String','0',...
    'Style','Edit',...
    'Tag','threshold');

gsobj.handles.rb_rising	= uicontrol('Unit','Normalized',...
    'Callback','set(findobj(gcf,''Tag'',''rb_falling''),''Value'',0)',...
    'Position',[0.787 0.142 0.024 0.051],...
    'String','A',...
    'Style','RadioButton',...
    'Tag','rb_rising',...
    'Value',1);

gsobj.handles.rb_falling   = uicontrol('Unit','Normalized',...
    'Callback','set(findobj(gcf,''Tag'',''rb_rising''),''Value'',0)',...
    'Position',[0.822 0.142 0.024 0.051],...
    'String','V',...
    'Style','RadioButton',...
    'Tag','rb_falling',...
    'Value',0);
