function getspike_pca
global gsobj

fig     = figure;
set(fig,'Name','GetSpike(PCA)',...
    'Numbertitle','Off',...
    'Pointer','arrow',...
    'Position',[810    102   613   393],...
    'Tag','gspca',...
    'Toolbar','Figure');

h   = subplot(6,1,1:5);
set(h,'Tag','pca_axis');

gsobj.handles.selectbutton  = uicontrol('Unit','Normalized',...
    'Callback','getspike(''pca_select'')',...
    'Position',[0.20 0.05 0.7 0.1],...
    'String','Select Data',...
    'Style','Pushbutton',...
    'Tag','selectbutton');

gsobj.handles.gspca     = fig;
gsobj.handles.pca       = h;

xlabel('PC1')
ylabel('PC2')