function indicator(varargin)
% INDICATOR ループの進捗具合をインジケータとして表示
% 
% INDICATOR(i,n)
% INDICATOR(i,n,text)
% 
% i       分子（何番目のループか）
% n       分母（全ループ回数）(0にするとインジケータfigureを閉じる)
% text    インジケータに付けるタイトル（オプション）
% 
% forループに入れ込むと、進捗状況および推定残り時間が表示される。
% インジケータを閉じるにはnに0を入力する（iはどんなものを入力しても構わない）
% 
% （例）
% 1から10までの数字を表示させるプログラムを走らせる際に、その進捗状況をインジケータとして表示する。
% 
% n   = 10;
% for ii=1:n
%     pause(1)      %　1秒待つ
%     disp(ii)      %　コマンドラインに数字を表示
%     indicator(ii,n,'sample');     %　インジケータに進捗状況を表示
% end
% pause(1)          % "100%"の画面を1秒間表示
% indicator(0,0)    % インジケータを閉じる
% written by TT       2007/12/25    

fig = findobj('Tag','indicator');
if nargin < 3
    c   = varargin{1};
    N   = varargin{2};
    titlestr    = [];
else
    c   = varargin{1};
    N   = varargin{2};
    titlestr    = varargin{3};
end

if N == 0
    close(fig);
    return;
else
    cp  = round((c/N)*100);
end

if(isempty(fig))
    % initialize
    S.clock = clock;
    S.cp    = cp;
    fig = figure('MenuBar','none',...
        'Name',[titlestr,'          ',num2str(cp),'%'],...
        'NumberTitle','off',...
        'Resize','off',...
        'Tag','indicator',...
        'ToolBar','none',...
        'Userdata',S,...
        'Position',[421 444 560 53]);
    h   = axes;
    set(h,'Nextplot','replacechildren',...
        'Box','on',...
        'Position',[0.1300    0.1855    0.7750    0.5504],...
        'XColor','w',...
        'XLim',[0 100],...
        'XTickMode','manual',...
        'XTick',[],...
        'XTickLabelMode','manual',...
        'XTickLabel',[],...
        'YColor','w',...
        'YLim',[0.9 1.1],...
        'YTickMode','manual',...
        'YTick',[],...
        'YTickLabelMode','manual',...
        'YTickLabel',[]);
    barh(h,cp,'r','EdgeColor','r');
    drawnow;
else
    S   = get(fig,'Userdata');
    if(S.cp > cp)
        S.clock = clock;
        S.cp    = cp;
        h   = get(fig,'Children');
        set(fig,'Name',[titlestr,'          ',num2str(cp),'%'],...
            'Userdata',S);
    else
        S.cp    = cp;
        t   = etime(clock,S.clock);
        et  = round((t / c) * (N - c));
        h   = get(fig,'Children');
        set(fig,'Name',[titlestr,'          ',num2str(cp),'%          Time remaining: ',num2str(et),' sec' ],...
            'Userdata',S)
    end
%     set(h,'Nextplot','replacechildren',...
%         'Box','off',...
%         'Position',[0.1300    0.1855    0.7750    0.5504],...
%         'XColor','w',...
%         'XLim',[0 100],...
%         'XTickMode','manual',...
%         'XTick',[],...
%         'XTickLabelMode','manual',...
%         'XTickLabel',[],...
%         'YColor','w',...
%         'YLim',[0.9 1.1],...
%         'YTickMode','manual',...
%         'YTick',[],...
%         'YTickLabelMode','manual',...
%         'YTickLabel',[]);
    barh(h,cp,'r','EdgeColor','r')
    drawnow;
end
