function initialize_file

fig   = figure('Name','ftcohtrig_btc',...
   'NumberTitle','off',...
   'MenuBar','figure',...
   'PaperOrientation','portrait',...
   'PaperPosition',[-2 4.91751 26.4382 19.8287],...%[-2.72314 4.91751 26.4382 19.8287]
   'PaperPositionMode','manual',...
   'PaperType','A4',...
   'Pointer','arrow',...
   'Resize','on',...
   'Units','pixels',...
   'UserData',[],...
   'Position',[161   469   450   315]);%[-922 37 448 903]

h.control  = uicontrol(fig,'BackgroundColor',[1 1 1],...
   'Style','listbox',...
   'HorizontalAlignment','center',...
   'Units','normalized',...
   'Position',[0.05 0.45 0.45 0.1],...
   'Tag','fileList',...
   'Max',0,...
   'Min',1,...
   'String','',...
   'Callback','');

h.list  = uicontrol(fig,'BackgroundColor',[1 1 1],...
   'Style','listbox',...
   'HorizontalAlignment','center',...
   'Units','normalized',...
   'Position',[0.05 0.05 0.45 0.1],...
   'Tag','fileList',...
   'Max',0,...
   'Min',1,...
   'String','',...
   'Callback','');

h.controlref  = uicontrol(fig,'BackgroundColor',get(fig,'Color'),...
   'Style','pushbutton',...
   'HorizontalAlignment','center',...
   'Units','normalized',...
   'Position',[0.5 0.45 0.45 0.1],...
   'Tag','fileList',...
   'Max',0,...
   'Min',1,...
   'String','reference',...
   'Callback','');

h.listref  = uicontrol(fig,'BackgroundColor',get(fig,'Color'),...
   'Style','pushbutton',...
   'HorizontalAlignment','center',...
   'Units','normalized',...
   'Position',[0.5 0.05 0.45 0.1],...
   'Tag','fileList',...
   'Max',0,...
   'Min',1,...
   'String','reference',...
   'Callback','');

h.OK  = uicontrol(fig,'BackgroundColor',get(fig,'Color'),...
   'Style','pushbutton',...
   'HorizontalAlignment','center',...
   'Units','normalized',...
   'Position',[0.05 0.05 0.45 0.1],...
   'Tag','fileList',...
   'Max',0,...
   'Min',1,...
   'String','OK',...
   'Callback','');

h.Cancel  = uicontrol(fig,'BackgroundColor',get(fig,'Color'),...
   'Style','pushbutton',...
   'HorizontalAlignment','center',...
   'Units','normalized',...
   'Position',[0.45 0.05 0.45 0.1],...
   'Tag','fileList',...
   'Max',0,...
   'Min',1,...
   'String','Cancel',...
   'Callback','');
