function answer  = matexplorer(currpath)

if(nargin<1)
    currpath    = getconfig(mfilename,'pathname');
    if(isempty(currpath))
        currpath    = pwd;
    end
    if(~exist(currpath,'dir'))
        currpath    = pwd;
    end
else
    if(~exist(currpath,'dir'))
        currpath    = pwd;
    end
end

UD  = makefigure;
UD.windrive = windrive;
UD.currpath = currpath;
UD.answer   = {};

set(UD.fig,'UserData',UD)
refreshpath;
applyfilter;

uiwait;


%%% resume from gui
try
    UD   = get(UD.fig,'UserData');
    close(UD.fig)

    % Deal with output argument
    answer        = UD.answer;
    setconfig(mfilename,'pathname',UD.currpath);
catch
    answer        = {};
end

end



function UD = makefigure

fig =figure('MenuBar','none',...
    'Name','Matlab Explorer',...
    'NumberTitle','off',...
    'PaperUnits', 'points',...
    'Position',[415 153 1221 863],...
    'Tag','matexplorer',...
    'Toolbar','figure');
centerfig(fig)


% uicontrol
figcolor    = get(fig,'Color');

h.addressframe  = uicontrol(fig,'BackgroundColor',figcolor,...
    'Style','frame',...
    'Units' , 'points',...
    'Position' , [30 610 45 20]);

h.addresslabel  = uicontrol(fig,'BackgroundColor',figcolor,...
    'FontName','Arial',...
    'FontSize',9,...
    'HorizontalAlignment','Left',...
    'String','Address',...
    'Style','text',...
    'Units' , 'points',...
    'Position' , [32 615 40 10]);

h.addressedit  = uicontrol(fig,'BackgroundColor',[1 1 1],...
    'Callback',@CB_addressbutton,...
    'FontName','Arial',...
    'FontSize',9,...
    'HorizontalAlignment','Left',...
    'String','   N:\test',...
    'Style','edit',...
    'Units' , 'points',...
    'Position' , [75 610 410 20]);

h.addressbutton  = uicontrol(fig,'BackgroundColor',figcolor,...
    'Callback',@CB_addressbutton,...
    'FontName','Arial',...
    'FontSize',9,...
    'HorizontalAlignment','center',...
    'String','>>',...
    'Style','pushbutton',...
    'Units' , 'points',...
    'Position' , [490 610 40 20]);

h.folderframe  = uicontrol(fig,'BackgroundColor',figcolor,...
    'Style','frame',...
    'Units' , 'points',...
    'Position' , [30 580 180 20]);

h.folderlabel  = uicontrol(fig,'BackgroundColor',figcolor,...
    'FontName','Arial',...
    'FontSize',9,...
    'HorizontalAlignment','Left',...
    'String','Folder',...
    'Style','text',...
    'Units' , 'points',...
    'Position' , [32 585 40 10]);

h.folderbox     = uicontrol(fig,'BackgroundColor',[1 1 1],...
    'Callback',@CB_folderbox,...
    'FontName','Arial',...
    'FontSize',9,...
    'Max',1,'Min',1,... % single selection
    'String',[],...
    'Style','listbox',...
    'Units' , 'points',...
    'Value' , [],...
    'Position' , [30 55  180 520]);

h.statusbar = uicontrol(fig,'BackgroundColor',figcolor,...
    'FontName','Arial',...
    'FontSize',9,...
    'HorizontalAlignment','left',...
    'String',[],...
    'Style','edit',...
    'Units' , 'points',...
    'Value' , [],...
    'Position' , [30 10  180 15]);

h.filtframe  = uicontrol(fig,'BackgroundColor',figcolor,...
    'Style','frame',...
    'Units' , 'points',...
    'Position' , [220 580 45 20]);

h.filtlabel  = uicontrol(fig,'BackgroundColor',figcolor,...
    'FontName','Arial',...
    'FontSize',9,...
    'HorizontalAlignment','Left',...
    'String','Filter',...
    'Style','text',...
    'Units' , 'points',...
    'Position' , [222 585 40 10]);

h.filtbox     = uicontrol(fig,'BackgroundColor',[1 1 1],...
    'Callback',@CB_filtbox,...
    'FontName','Arial',...
    'FontSize',8,...
    'HorizontalAlignment','left',...
    'String',[],...
    'Style','Edit',...
    'Units' , 'points',...
    'Value' , [],...
    'Position' , [265 580 245 20]);

h.filtbutton    = uicontrol(fig,'BackgroundColor',figcolor,...
    'Callback',@CB_filtbutton,...
    'FontName','Arial',...
    'FontSize',9,...
    'HorizontalAlignment','center',...
    'String','[x]',...
    'Style','pushbutton',...
    'Units' , 'points',...
    'Value' , [],...
    'Position' , [510 580 20  20]);


h.filebox     = uicontrol(fig,'BackgroundColor',[1 1 1],...
    'FontName','Arial',...
    'FontSize',9,...
    'Max',100,'Min',1,... % Multiple selection
    'String',[],...
    'Style','listbox',...
    'Units' , 'points',...
    'Value' , 1,...
    'Position' , [220 55  310 520]);

h.resultframe  = uicontrol(fig,'BackgroundColor',figcolor,...
    'Style','frame',...
    'Units' , 'points',...
    'Position' , [590 610 45 20]);

h.resultlabel  = uicontrol(fig,'BackgroundColor',figcolor,...
    'FontName','Arial',...
    'FontSize',9,...
    'HorizontalAlignment','Left',...
    'String','Result',...
    'Style','text',...
    'Units' , 'points',...
    'Position' , [592 615 40 10]);

h.resultbox     = uicontrol(fig,'BackgroundColor',figcolor,...
    'Callback',[],...
    'FontName','Arial',...
    'FontSize',9,...
    'HorizontalAlignment','center',...
    'String',[],...
    'Style','edit',...
    'Units' , 'points',...
    'Value' , [],...
    'Position' , [635 610 265 20]);

h.defansframe  = uicontrol(fig,'BackgroundColor',figcolor,...
    'Style','frame',...
    'Units' , 'points',...
    'Position' , [590 580 45 20]);

h.defanslabel  = uicontrol(fig,'BackgroundColor',figcolor,...
    'FontName','Arial',...
    'FontSize',9,...
    'HorizontalAlignment','Left',...
    'String','Filter',...
    'Style','text',...
    'Units' , 'points',...
    'Position' , [592 585 40 10]);

h.defansbox     = uicontrol(fig,'BackgroundColor',[1 1 1],...
    'Callback',@CB_defansbox,...
    'Enable','off',...
    'FontName','Arial',...
    'FontSize',9,...
    'HorizontalAlignment','left',...
    'String',[],...
    'Style','edit',...
    'Units' , 'points',...
    'Value' , [],...
    'Position' , [635 580 265 20]);

h.answerbox = uicontrol(fig,'BackgroundColor',[1 1 1],...
    'FontName','Arial',...
    'FontSize',9,...
    'Max',100,...
    'Min',1,...
    'String',[],...
    'Style','listbox',...
    'Units' , 'points',...
    'Value' , [],...
    'Position' , [590 55  310 520]);

h.add   = uicontrol(fig,'BackgroundColor',get(fig,'Color'),...
    'Callback',@CB_add,...
    'FontName','Arial',...
    'FontSize',9,...
    'Style','Pushbutton',...
    'Units' , 'points',...
    'Position' , [542 510 36 36],...
    'String','>');

h.delete    = uicontrol(fig,'BackgroundColor',get(fig,'Color'),...
    'Callback',@CB_delete,...
    'FontName','Arial',...
    'FontSize',9,...
    'Style','Pushbutton',...
    'Units' , 'points',...
    'Position' , [542 462 36 36],...
    'String','<');

h.add_all   = uicontrol(fig,'BackgroundColor',get(fig,'Color'),...
    'Callback',@CB_add_all,...
    'FontName','Arial',...
    'FontSize',9,...
    'Style','Pushbutton',...
    'Units' , 'points',...
    'Position' , [542 414 36 36],...
    'String','>>');

h.delete_all    = uicontrol(fig,'BackgroundColor',get(fig,'Color'),...
    'Callback',@CB_delete_all,...
    'FontName','Arial',...
    'FontSize',9,...
    'Style','Pushbutton',...
    'Units' , 'points',...
    'Position' , [542 366 36 36],...
    'String','<<');

h.up        = uicontrol(fig,'BackgroundColor',get(fig,'Color'),...
    'Callback',@CB_up,...
    'FontName','Arial',...
    'FontSize',9,...
    'Style','Pushbutton',...
    'Units' , 'points',...
    'Position' , [542 318 36 36],...
    'String','A');

h.top       = uicontrol(fig,'BackgroundColor',get(fig,'Color'),...
    'Callback',@CB_top,...
    'FontName','Arial',...
    'FontSize',9,...
    'Style','Pushbutton',...
    'Units' , 'points',...
    'Position' , [542 270 36 36],...
    'String','AA');

h.down      = uicontrol(fig,'BackgroundColor',get(fig,'Color'),...
    'Callback',@CB_down,...
    'FontName','Arial',...
    'FontSize',9,...
    'Style','Pushbutton',...
    'Units' , 'points',...
    'Position' , [542 222 36 36],...
    'String','V');

h.bottom     = uicontrol(fig,'BackgroundColor',get(fig,'Color'),...
    'Callback',@CB_bottom,...
    'FontName','Arial',...
    'FontSize',9,...
    'Style','Pushbutton',...
    'Units' , 'points',...
    'Position' , [542 174 36 36],...
    'String','VV');

h.ok        = uicontrol(fig,'BackgroundColor',get(fig,'Color'),...
    'Callback',@CB_ok,...
    'Style','Pushbutton',...
    'Units' , 'points',...
    'Position' , [635 10 100 36],...
    'String','OK');

h.cancel    = uicontrol(fig,'BackgroundColor',get(fig,'Color'),...
    'Callback',@CB_cancel,...
    'FontName','Arial',...
    'FontSize',9,...
    'Style','Pushbutton',...
    'Units' , 'points',...
    'Position' , [765 10 100 36],...
    'String','Cancel');

set(get(fig,'children'),'Units','normalize')


% uimenu
h.menu.file  =  uimenu(fig,'Label','&File');
h.menu.openlist  =  uimenu(h.menu.file,'Label','Open List',...
    'Callback',@CB_openlist,...
    'Enable','on',...
    'Accelerator','o');

h.menu.savefile   =  uimenu(h.menu.file,'Label','Save List',...
    'Callback',@CB_savelist,...
    'Enable','on',...
    'Accelerator','s');



UD.fig           = fig;
UD.h             = h;

end

function [fullpathtree,fullpath,currpathind]    = makefullpathtree(currpath,otherpath)

notherpath      = length(otherpath);

[currpathparts,currpath]    = parsepath(currpath);
currlevel       = length(currpathparts);

children    = cell(1,currlevel);
nchildren   = zeros(1,currlevel);

for ilevel  =1:currlevel
    children{ilevel}    = sort(dirdir(fullfile(currpathparts{1:ilevel},filesep)));
    nchildren(ilevel)   = length(children{ilevel});
end

nfullpath   = notherpath + sum(nchildren);
fullpath    = cell(nfullpath,1);


fullpath(1:notherpath)   = otherpath;

ifullpath   = notherpath;
for ilevel =1:currlevel
    for ichildren =1:nchildren(ilevel)
        ifullpath   = ifullpath + 1;
        fullpath{ifullpath} = fullfile(currpathparts{1:ilevel},children{ilevel}{ichildren});
    end
end

fullpath    = sort(fullpath);
currpathind = strmatch(currpath,fullpath,'exact');


% make fullpathtree
fullpathtree    = cell(size(fullpath));

for ifullpath =1:nfullpath
    X   = fullpath{ifullpath};
    if(~strcmp(X(1),filesep))
        X   = [filesep,X];
    end
    if(~strcmp(X(end),filesep))
        X   = [X,filesep];
    end

    ind     = strfind(X,filesep);
    level   = length(ind) - 1;

    if(strmatch(fullpath{ifullpath},currpath))
        select_icon   = '[-]';
    else
        select_icon   = '[+]';
    end

    fullpathtree{ifullpath}   = [repmat('    ',1,level),select_icon,' ',X((ind(end-1)+1):(ind(end)-1))];
end
end

function refreshpath
UD  = get(gcf,'UserData');
set(UD.h.statusbar,'String','Processing...'),drawnow;

[UD.fullpathtree,UD.fullpath,UD.currpathind]    = makefullpathtree(UD.currpath,UD.windrive);

filterstring    = get(UD.h.filtbox,'String');
if(isempty(filterstring))
    UD.currfiles    = sort(strfilt(dirmat(UD.currpath),'~._'));
else
    UD.currfiles    = sort(strfilt(dirmat(UD.currpath),'~._'));
    UD.currfiles    = strfilt(UD.currfiles,filterstring);
end

set(UD.fig,'Name',UD.currpath)
set(UD.h.addressedit,'String',UD.currpath);
set(UD.h.folderbox,'String',UD.fullpathtree,...
    'Value',UD.currpathind);
set(UD.h.filebox,'String',UD.currfiles,...
    'Value',[])
set(UD.h.answerbox,'String',UD.answer,...
    'Value',[])
set(UD.h.resultbox,'String',[' ',num2str(length(UD.answer)),' objects.']);

set(UD.fig,'UserData',UD)
set(UD.h.statusbar,'String','Done.'),drawnow;
end

function applyfilter
UD  = get(gcf,'UserData');

filterstring    = get(UD.h.filtbox,'String');
if(isempty(filterstring))
    UD.currfiles    = sort(strfilt(dirmat(UD.currpath),'~._'));
else
    UD.currfiles    = sort(strfilt(dirmat(UD.currpath),'~._'));
    UD.currfiles    = strfilt(UD.currfiles,filterstring);
end

set(UD.h.filebox,'String',UD.currfiles,...
    'Value',[])
set(UD.fig,'UserData',UD)
end

function CB_openlist(varargin)
UD  = get(gcf,'UserData');
set(UD.h.statusbar,'String','Loading...'),drawnow;

listfile    = getconfig('matexplorer','listfile');
listpath    = getconfig('matexplorer','listpath');

[listfile, listpath] = uigetfile(fullfile(listpath,listfile), 'Open List');


answer  = load(fullfile(listpath,listfile),'answer');
answer  = answer.answer;

UD.answer   = answer;
setconfig(mfilename,'listfile',listfile);
setconfig(mfilename,'listpath',listpath);

set(UD.fig,'UserData',UD)

refreshpath;
set(UD.h.statusbar,'String','Done...'),drawnow;
end

function CB_savelist(varargin)
UD  = get(gcf,'UserData');
set(UD.h.statusbar,'String','Saving...'),drawnow;

answer  = UD.answer;

listfile    = getconfig('matexplorer','listfile');
listpath    = getconfig('matexplorer','listpath');

[listfile, listpath] = uiputfile(fullfile(listpath,listfile), 'Save List as');

save(fullfile(listpath,listfile),'answer')

setconfig(mfilename,'listfile',listfile);
setconfig(mfilename,'listpath',listpath);

set(UD.h.statusbar,'String','Done...'),drawnow;
end

function CB_folderbox(varargin)
UD  = get(gcf,'UserData');

UD.currpathind  = get(UD.h.folderbox,'Value');
UD.currpath     = UD.fullpath{UD.currpathind};

set(UD.fig,'UserData',UD)

refreshpath;
% applyfilter;
end

function CB_addressbutton(varargin)
UD  = get(gcf,'UserData');
currpath    = get(UD.h.addressedit,'String');

if(~isempty(strfind(currpath,':')) && isempty(strfind(currpath,[':',filesep])) )
    ind = strfind(currpath,':');
    currpath    = fullfile(currpath(1:ind(1)),currpath(ind(1)+1:end));
end
if(strcmp(currpath(end),filesep))
    currpath(end)   = [];
end

if(exist(currpath,'dir'))
    UD.currpath = currpath;
    set(UD.fig,'UserData',UD)
end

refreshpath;

end

function CB_filtbox(varargin)
applyfilter;
end

function CB_filtbutton(varargin)
UD  = get(gcf,'UserData');
set(UD.h.filtbox,'String',[]);
applyfilter;
end

function CB_defansbox(varargin)
end

function CB_add(varargin)
UD  = get(gcf,'UserData');

add_files   = UD.currfiles(get(UD.h.filebox,'Value'));

nfiles      = length(add_files);
for ifile   = 1:nfiles
    add_files{ifile}    = fullfile(UD.currpath,add_files{ifile});
end
UD.answer   = [UD.answer,setdiff(add_files,UD.answer)];   % 重複するものは新たに加えない
[TF,add_ind]= ismember(add_files,UD.answer);

set(UD.h.answerbox,'String',UD.answer,'Value',add_ind(add_ind~=0));
set(UD.h.resultbox,'String',[' ',num2str(length(UD.answer)),' objects.']);

set(UD.fig,'UserData',UD)
end

function CB_delete(varargin)
UD  = get(gcf,'UserData');

add_ind     = get(UD.h.answerbox,'Value');


UD.answer(add_ind)   = [];

set(UD.h.answerbox,'String',UD.answer,'Value',[]);
set(UD.h.resultbox,'String',[' ',num2str(length(UD.answer)),' objects.']);

set(UD.fig,'UserData',UD)
end

function CB_add_all(varargin)
UD  = get(gcf,'UserData');

add_files   = UD.currfiles;

nfiles      = length(add_files);
for ifile   = 1:nfiles
    add_files{ifile}    = fullfile(UD.currpath,add_files{ifile});
end

UD.answer   = [UD.answer,setdiff(add_files,UD.answer)];   % 重複するものは新たに加えない
[TF,add_ind]= ismember(add_files,UD.answer);

set(UD.h.answerbox,'String',UD.answer,'Value',add_ind(add_ind~=0));
set(UD.h.filebox,'Value',[]);
set(UD.h.resultbox,'String',[' ',num2str(length(UD.answer)),' objects.']);

set(UD.fig,'UserData',UD)
end

function CB_delete_all(varargin)
UD  = get(gcf,'UserData');

UD.answer   = {};

set(UD.h.answerbox,'String',UD.answer,'Value',[]);
set(UD.h.filebox,'Value',[]);
set(UD.h.resultbox,'String',[' ',num2str(length(UD.answer)),' objects.']);

set(UD.fig,'UserData',UD)
end

function CB_up(varargin)
UD  = get(gcf,'UserData');

old_answer  = UD.answer;
selected_ind    = get(UD.h.answerbox,'Value');
if(length(old_answer)<2 || isempty(selected_ind))
    return
end

all_ind     = 1:length(UD.answer);
unselected_ind  = setdiff(all_ind,selected_ind);
new_selected_ind = selected_ind - 1;
if(min(new_selected_ind)<1)
    return
end
new_unselected_ind  = setdiff(all_ind,new_selected_ind);

UD.answer(new_selected_ind) = old_answer(selected_ind);
UD.answer(new_unselected_ind) = old_answer(unselected_ind);

set(UD.h.answerbox,'String',UD.answer,'Value',new_selected_ind);

set(UD.fig,'UserData',UD)
end

function CB_top(varargin)
UD  = get(gcf,'UserData');

old_answer      = UD.answer;
selected_ind    = get(UD.h.answerbox,'Value');
if(length(old_answer)<2 || isempty(selected_ind))
    return
end

all_ind         = 1:length(UD.answer);
unselected_ind  = setdiff(all_ind,selected_ind);
new_selected_ind= 1:length(selected_ind);
new_unselected_ind  = setdiff(all_ind,new_selected_ind);

UD.answer(new_selected_ind) = old_answer(selected_ind);
UD.answer(new_unselected_ind) = old_answer(unselected_ind);

set(UD.h.answerbox,'String',UD.answer,'Value',new_selected_ind);

set(UD.fig,'UserData',UD)
end

function CB_down(varargin)
UD  = get(gcf,'UserData');

old_answer  = UD.answer;
selected_ind    = get(UD.h.answerbox,'Value');
if(length(old_answer)<2 || isempty(selected_ind))
    return
end

all_ind     = 1:length(UD.answer);
unselected_ind  = setdiff(all_ind,selected_ind);
new_selected_ind = selected_ind + 1;
if(max(new_selected_ind)>all_ind(end))
    return
end
new_unselected_ind  = setdiff(all_ind,new_selected_ind);

UD.answer(new_selected_ind) = old_answer(selected_ind);
UD.answer(new_unselected_ind) = old_answer(unselected_ind);

set(UD.h.answerbox,'String',UD.answer,'Value',new_selected_ind);

set(UD.fig,'UserData',UD)
end

function CB_bottom(varargin)
UD  = get(gcf,'UserData');

old_answer  = UD.answer;
selected_ind    = get(UD.h.answerbox,'Value');
if(length(old_answer)<2 || isempty(selected_ind))
    return
end

all_ind     = 1:length(UD.answer);
unselected_ind  = setdiff(all_ind,selected_ind);
new_selected_ind = (all_ind(end)-length(selected_ind)+1):all_ind(end);

new_unselected_ind  = setdiff(all_ind,new_selected_ind);

UD.answer(new_selected_ind) = old_answer(selected_ind);
UD.answer(new_unselected_ind) = old_answer(unselected_ind);

set(UD.h.answerbox,'String',UD.answer,'Value',new_selected_ind);

set(UD.fig,'UserData',UD)
end

function CB_ok(varargin)
uiresume;

end

function CB_cancel(varargin)
UD  = get(gcf,'UserData');
UD.answer   = {};
set(UD.fig,'UserData',UD)
uiresume;

end