function s  = packPSE(s,psename)
% PSE‚Ìƒf[ƒ^‚ª•Ï”‚Ì’¼‰º‚É‚ ‚éó‘Ô‚©‚ç®—

if(isfield(s,'base'))
    items   = {'nsd',...
        'nnsec',...
        'kksec',...
        'alpha',...
        'nSPF',...
        'nMF'};

    nitems  = length(items);

    for iitem=1:nitems
        item    = items{iitem};
        if(isfield(s.base,item))
            s.(psename).(item)    = s.base.(item);
            if(isfield(s.(psename),item))
                s.base  = rmfield(s.base,item);
            end
        end
    end
end

items   = {'method',...
    'pind',...
    'tind',...
    'base',...
    'npeaks',...
    'nsigpeaks',...
    'sigpeakind',...
    'nsigpeaks_ttest',...
    'sigpeakind_ttest',...
    'peaks',...
    'maxsigpeakind',...
    'maxsigpeakind_ttest',...
    'isXtalk',...
    'search_TimeWindow',...
    'search_Object',...
    'npeaksTW',...
    'peakindTW',...
    'nsigpeaksTW',...
    'sigpeakindTW',...
    'maxsigpeakindTW',...
    'nsigpeaks_ttestTW',...
    'sigpeakind_ttestTW',...
    'maxsigpeakind_ttestTW'};

nitems  = length(items);

for iitem=1:nitems
    item    = items{iitem};
    if(isfield(s,item))
        s.(psename).(item)    = s.(item);
        if(isfield(s,item))
            s   = rmfield(s,item);
        end
    end
end