function y=parseEMG(x,X)
if(nargin<2)
    y   = parseEMG2(x);
else
    xx  = parseEMG2(x);
    XX  = parseEMG2(X);
    ind = strmatch(xx,XX,'exact');
    
    y   = X{ind};
    
end



end

function y=parseEMG2(x)
EMG = {'2DI',...
    '3DI',...
    '4DI',...
    'AbDM',...
    'AbPB',...
    'AbPL',...
    'ADP',...
    'Biceps',...
    'BRD',...
    'ECR',...
    'ECU',...
    'ED23',...
    'EDC',...
    'FCR',...
    'FCU',...
    'FDI',...
    'FDPr',...
    'FDPu',...
    'FDS',...
    'FPB',...
    'PL',...
    'Triceps',...
    'ECRl',...
    'ECRb',...
    'PT',...
    'ED45'};


nEMG    = length(EMG);
if(ischar(x))
    x   = {x};
end
nx      = length(x);
y       = cell(size(x));

for ix=1:nx
    xx  = x{ix};


    ind     = [];
    for iEMG=1:nEMG
        if(strfind(xx,EMG{iEMG}))
            ind = [ind,iEMG];
        end
    end

    if(isempty(ind))
        y{ix}   = [];
    elseif(length(ind)==1)
        y{ix}   = EMG{ind};
    else
        L   = zeros(1,length(ind));
        for iind =1:length(ind)
            L(iind) = length(EMG{ind(iind)});
        end
        [M,I]   = max(L);
        y{ix}   = EMG{ind(I)};
    end
end
if(length(y)==1)
    y   = y{1};
end
end


