function varargout  = pplot(varargin)

H   = plot(varargin{:});
S   = get(H);

set(H,'LineStyle','o',...
    'MarkerEdgeColor',S.Color,...
    'MarkerFaceColor',S.Color,...
    'MarkerSize',3,...
    'XData',repmat(S.XData,1,3),...
    'YData',[S.YData-2*pi, S.YData, S.YData+2*pi]);


set(gca,'yLim',[-2*pi 2*pi],...
    'yTickMode','manual',...
    'yTick',[-3*pi -2*pi -pi 0 pi 2*pi 3*pi],...
    'yTickLabel',{'-3pi' '-2pi' '-pi' '0' 'pi' '2pi' '3pi'})

if nargout>0
    varargout{1}    = H;
end