function [restEMG,gripEMG,holdEMG] = taskphasecomp_EMG

files   = {'L:\tkitom\MDAdata\Analyses\STA\AobaT01108\STA (Grip Onset (success valid), FDPu-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT00302\STA (Grip Onset (success valid), FDI-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT00201\STA (Grip Onset (success valid), FDPr-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT02405\STA (Grip Onset (success valid), FDPr-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT00203\STA (Grip Onset (success valid), BB-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT00203\STA (Grip Onset (success valid), ED23-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT00201\STA (Grip Onset (success valid), AbDM-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT00203\STA (Grip Onset (success valid), ECU-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT00903\STA (Grip Onset (success valid), BRD-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT00907\STA (Grip Onset (success valid), BRD-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT00201\STA (Grip Onset (success valid), ADP-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT01108\STA (Grip Onset (success valid), AbPB-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT01108\STA (Grip Onset (success valid), ADP-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT01114\STA (Grip Onset (success valid), FCR-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT00101\STA (Grip Onset (success valid), FDI-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT00302\STA (Grip Onset (success valid), FDS-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT00903\STA (Grip Onset (success valid), FDS-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT01105\STA (Grip Onset (success valid), PL-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT01108\STA (Grip Onset (success valid), BRD-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT01114\STA (Grip Onset (success valid), PL-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT00302\STA (Grip Onset (success valid), AbPB-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT00302\STA (Grip Onset (success valid), FDPr-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT00903\STA (Grip Onset (success valid), AbPB-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT00903\STA (Grip Onset (success valid), PT-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT00907\STA (Grip Onset (success valid), ADP-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT01108\STA (Grip Onset (success valid), FDPr-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT01108\STA (Grip Onset (success valid), FDS-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT01108\STA (Grip Onset (success valid), PL-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT01114\STA (Grip Onset (success valid), FDPr-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT02401\STA (Grip Onset (success valid), AbPB-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT00101\STA (Grip Onset (success valid), BRD-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT00301\STA (Grip Onset (success valid), BB-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT00301\STA (Grip Onset (success valid), PL-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT00301\STA (Grip Onset (success valid), PT-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT00302\STA (Grip Onset (success valid), PL-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT01105\STA (Grip Onset (success valid), AbPB-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT01108\STA (Grip Onset (success valid), FDI-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT02405\STA (Grip Onset (success valid), AbDM-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT00201\STA (Grip Onset (success valid), BRD-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT01101\STA (Grip Onset (success valid), AbPB-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT01114\STA (Grip Onset (success valid), FCU-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT02405\STA (Grip Onset (success valid), BRD-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT02405\STA (Grip Onset (success valid), FCU-subsample(uV)).mat'};

files   = {'L:\tkitom\MDAdata\Analyses\STA\AobaT00203\STA (Grip Onset (success valid), FDPr-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT00203\STA (Grip Onset (success valid), FDI-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT02405\STA (Grip Onset (success valid), AbPB-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT00203\STA (Grip Onset (success valid), ADP-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT00203\STA (Grip Onset (success valid), FDPu-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT00203\STA (Grip Onset (success valid), AbDM-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT00203\STA (Grip Onset (success valid), BRD-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT02405\STA (Grip Onset (success valid), ADP-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT00203\STA (Grip Onset (success valid), AbPB-subsample(uV)).mat',...
    'L:\tkitom\MDAdata\Analyses\STA\AobaT00302\STA (Grip Onset (success valid), ADP-subsample(uV)).mat'};
files   = {'L:\tkitom\MDAdata\Analyses\STA\AobaT00907\STA (Grip Onset (success valid), ADP-subsample(uV)).mat'};

for ii = 1:length(files)
s   = load(files{ii});


trest    = [82 :181];
tgrip    = [232:331];
thold    = [607:706];

nYData   = normalize(s.YData,'max');

restEMG(ii)     = mean(nYData(trest));
gripEMG(ii)     = mean(nYData(tgrip));
holdEMG(ii)     = mean(nYData(thold));
indicator(ii,length(files))
end
indicator(0,0)





