function tcohsurveydepth_print2

warning('off')
% rootpath    = 'L:\tkitom\data\tcohsurvey\080619_EndHold';
% rootpath    = 'L:\tkitom\data\tcohsurvey\080619_GripOn';
% rootpath    = 'L:\tkitom\data\tcohsurvey\080619_PreGripOn';

% rootpath    = 'L:\tkitom\data\tcohsurvey\080624_GripOn';
% rootpath    = 'L:\tkitom\data\tcohsurvey\080624_EndHold';

% rootpath    = 'L:\tkitom\data\tcohsurvey\080711_GripOn';
% rootpath    = 'L:\tkitom\data\tcohsurvey\080711_EndHold';

rootpath    = fullfile(datapath,'tcohsurvey\080717');

% Expnames    = {'EitoT001';...
%     'EitoT002';...    'EitoT003';...
%     'EitoT004';...
%     'EitoT005';...
%     'EitoT006';...
%     'EitoT007';...
%     'EitoT008';...
%     'EitoT009';...
%     'EitoT010';...
%     'EitoT011';...
%     'EitoT012';...
%     'EitoT013';...
%     'EitoT014';...
%     'EitoT015';...
%     'EitoT016';...
%     'EitoT017';...
%     'EitoT018';...
%     'EitoT019';...    'EitoT020';...
%     'EitoT021';...    'EitoT022';...
%     'EitoT023';...
%     'EitoT024';...
%     'EitoT025';...
%     'EitoT026';...
%     'EitoT027';...
%     'EitoC013';...
%     'EitoC014';...
%     'EitoC015';...
%     'EitoC016';...
%     'EitoC017';...
%     'EitoC018';...
%     'EitoC019';...
%     'EitoC020';...
%     'EitoC021'};

% Expnames    = {'EitoC034',...
%     'EitoC035',...
%     'EitoC036'};
Expnames    = {'EitoT002',...
    'EitoT004',...
    'EitoT005',...
    'EitoT009',...
    'EitoT010',...
    'EitoT019'};
% Expnames    = {'EitoT002'};

fieldname   = 'Field 1-subsample';
% fieldname   = 'Field 2-subsample';
% fieldname   = 'Field 3-subsample';
ddepth      = 0.250;
sdepth      = 1.0;
DOI         = [0.5 3.5];
FOI         = [0 100];
NBFOI       = [9:17];  % ind 9
BBFOI       = [9:48];  % ind 40



Trignames   = {'Grip Onset (svwostim)(down-0-1000)';...
    'Grip Onset (svwostim)(down-250-1250)';...
    'Grip Onset (svwostim)(down-500-1500)';...
    'Grip Onset (svwostim)(down-750-1750)';...
    'Grip Onset (svwostim)(down-1000-2000)';...
    'Grip Onset (svwostim)(down-1250-2250)';...
    'Grip Onset (svwostim)(down-1500-2500)';...
    'Grip Onset (svwostim)(down-1750-2750)';...
    'Grip Onset (svwostim)(down-2000-3000)';...
    'Grip Onset (svwostim)(down-2250-3250)';...
    'Grip Onset (svwostim)(down-2500-3500)';...
    'Grip Onset (svwostim)(down-2750-3750)';...
    'Grip Onset (svwostim)(down-3000-4000)'};

% Trignames   = {'Grip Onset (svwostim)(up-0-1000)',...
%     'Grip Onset (svwostim)(up-500-1500)',...
%     'Grip Onset (svwostim)(up-1000-2000)',...
%     'Grip Onset (svwostim)(up-1500-2500)',...
%     'Grip Onset (svwostim)(up-2000-3000)',...
%     'Grip Onset (svwostim)(up-2500-3500)',...
%     'Grip Onset (svwostim)(up-3000-4000)'};

% Trignames   = {'Grip Onset (svwostim)(all-0-1000)',...
%     'Grip Onset (svwostim)(all-500-1500)',...
%     'Grip Onset (svwostim)(all-1000-2000)',...
%     'Grip Onset (svwostim)(all-1500-2500)',...
%     'Grip Onset (svwostim)(all-2000-3000)',...
%     'Grip Onset (svwostim)(all-2500-3500)',...
%     'Grip Onset (svwostim)(all-3000-4000)'};

% EMGnames   = {'FDI-subsample',...%
%     '2DI-subsample',...
%     '3DI-subsample',...
%     '4DI-subsample',...
%     'ADP-subsample',...
%     'AbPB-subsample',...
%     'AbDM-subsample',...
%     'FDS-subsample',...
%     'FDPr-subsample',...
%     'FDPu-subsample',...
%     'PL-subsample',...
%     'FCR-subsample',...
%     'FCU-subsample',...
%     'AbPL-subsample',...
%     'ED23-subsample',...
%     'EDC-subsample',...
%     'ECR-subsample',...
%     'ECU-subsample',...
%     'BRD-subsample',...
%     'Biceps-subsample',...
%     'Triceps-subsample'};

EMGnames   = {'FDI-subsample',...%
    '2DI-subsample',...
    '3DI-subsample',...
    '4DI-subsample',...
    'ADP-subsample',...
    'AbPB-subsample',...
    'AbDM-subsample',...
    'FDS-subsample',...
    'FDPr-subsample',...
    'FDPu-subsample',...
    'PL-subsample',...
    'FCR-subsample',...
    'FCU-subsample',...
    'AbPL-subsample',...
    'ED23-subsample',...
    'EDC-subsample',...
    'ECR-subsample',...
    'ECU-subsample',...
    'BRD-subsample',...
    'Biceps-subsample'};



nExp    = length(Expnames);
nEMG    = length(EMGnames);
nTrig   = length(Trignames);

for iExp    = 1:nExp
    try
    Expname     = Expnames{iExp};
    
    fig = open('A4land.fig');
    set(fig,'Name',Expname,...
        'FileName',Expname,...
        'Color',[1 1 1])
    for iEMG   = 1:nEMG
        EMGname     = EMGnames{iEMG};
        if(iEMG==20&(strcmp(Expname,'EitoT009')|strcmp(Expname,'EitoT010')))
            EMGname = 'Triceps-subsample';
        end
        jj  = 0;
        for iTrig   = 1:nTrig
            Trigname    = Trignames{iTrig};
            filename    = fullfile(rootpath,[Expname,'_',fieldname,'_',EMGname,'_',Trigname]);
%             keyboard
            s   = load(filename);
            if(s.cl.seg_tot>20)
                jj   = jj + 1;
                Depth(jj)   = (iTrig-1)*ddepth+(sdepth/2);
                coh(jj,:)     = s.f.coh;
%                 PSD11(jj,:)   = s.f.PSD11;
%                 PSD22(jj,:)   = s.f.PSD22;
            end
            if(s.cl.seg_tot>20)
                eval(['mcoh.',Expname,'.NB(',num2str(iEMG),',',num2str(iTrig),')=mean(s.f.coh(NBFOI));']);
                eval(['mcoh.',Expname,'.BB(',num2str(iEMG),',',num2str(iTrig),')=mean(s.f.coh(BBFOI));']);
                eval(['sigcnt.',Expname,'.NB(',num2str(iEMG),',',num2str(iTrig),')=sum(s.f.coh(NBFOI)>s.cl.ch_c95);']);
                eval(['sigcnt.',Expname,'.BB(',num2str(iEMG),',',num2str(iTrig),')=sum(s.f.coh(BBFOI)>s.cl.ch_c95);']);
            else
                eval(['mcoh.',Expname,'.NB(',num2str(iEMG),',',num2str(iTrig),')=NaN;']);
                eval(['mcoh.',Expname,'.BB(',num2str(iEMG),',',num2str(iTrig),')=NaN;']);
                eval(['sigcnt.',Expname,'.NB(',num2str(iEMG),',',num2str(iTrig),')=NaN;']);
                eval(['sigcnt.',Expname,'.BB(',num2str(iEMG),',',num2str(iTrig),')=NaN;']);
            end
        end
%         PSD11(:,1)  = 0;
%         PSD22(:,1)  = 0;
        
        freq    = s.f.freq(:);
%         nDepth  = nTrig;
%         Depth   = ([1:nDepth]-1)*ddepth;

        

        h   = subplot(4,5,iEMG);
        pcolor(freq,Depth,coh); shading interp
        set(gca,'clim',[cohcl(0.05,50) 0.3],...
            'YDir','Reverse',...
                'YLim',DOI,...
                'XLim',FOI)
        colormap(tmap2)
        if(iEMG==1)
           title({rootpath;Expname;datestr(now)})
        end
        ylabel(EMGname)
%         title('coh')
    end
%     print(fig)
%     close(fig)
    disp([Expname, ' was printed out'])
    catch
        Expname     = Expnames{iExp};
        disp(['error occured in',Expname])
    end
end

save('mcoh','mcoh')
save('sigcnt','sigcnt')

warning('on')

