function tcohsurveydepth_print
% rootpath    = 'L:\tkitom\data\tcohsurvey\080619_EndHold';
% rootpath    = 'L:\tkitom\data\tcohsurvey\080619_GripOn';
% rootpath    = 'L:\tkitom\data\tcohsurvey\080619_PreGripOn';

% rootpath    = 'L:\tkitom\data\tcohsurvey\080624_GripOn';
% rootpath    = 'L:\tkitom\data\tcohsurvey\080624_EndHold';

% rootpath    = 'L:\tkitom\data\tcohsurvey\080711_GripOn';
% rootpath    = 'L:\tkitom\data\tcohsurvey\080711_EndHold';

rootpath    = fullfile(datapath,'tcohsurvey\080717');

% Expnames    = {'EitoT001';...
%     'EitoT002';...    'EitoT003';...
%     'EitoT004';...
%     'EitoT005';...
%     'EitoT006';...
%     'EitoT007';...
%     'EitoT008';...
%     'EitoT009';...
%     'EitoT010';...
%     'EitoT011';...
%     'EitoT012';...
%     'EitoT013';...
%     'EitoT014';...
%     'EitoT015';...
%     'EitoT016';...
%     'EitoT017';...
%     'EitoT018';...
%     'EitoT019';...    'EitoT020';...
%     'EitoT021';...    'EitoT022';...
%     'EitoT023';...
%     'EitoT024';...
%     'EitoT025';...
%     'EitoT026';...
%     'EitoT027';...
%     'EitoC013';...
%     'EitoC014';...
%     'EitoC015';...
%     'EitoC016';...
%     'EitoC017';...
%     'EitoC018';...
%     'EitoC019';...
%     'EitoC020';...
%     'EitoC021'};

% Expnames    = {'EitoC034',...
%     'EitoC035',...
%     'EitoC036'};
Expnames    = {'EitoT002',...
    'EitoT004',...
    'EitoT005',...
    'EitoT009',...
    'EitoT010',...
    'EitoT019'};
Expnames    = {'EitoT010'};

fieldname   = 'Field 1-subsample';
% fieldname   = 'Field 2-subsample';
% fieldname   = 'Field 3-subsample';
ddepth      = 0.250;
DOI         = [0 3];
FOI         = [0 100];
Trignames   = {'Grip Onset (svwostim)(down-0-1000)';...
    'Grip Onset (svwostim)(down-250-1250)';...
    'Grip Onset (svwostim)(down-500-1500)';...
    'Grip Onset (svwostim)(down-750-1750)';...
    'Grip Onset (svwostim)(down-1000-2000)';...
    'Grip Onset (svwostim)(down-1250-2250)';...
    'Grip Onset (svwostim)(down-1500-2500)';...
    'Grip Onset (svwostim)(down-1750-2750)';...
    'Grip Onset (svwostim)(down-2000-3000)';...
    'Grip Onset (svwostim)(down-2250-3250)';...
    'Grip Onset (svwostim)(down-2500-3500)';...
    'Grip Onset (svwostim)(down-2750-3750)';...
    'Grip Onset (svwostim)(down-3000-4000)'};

% Trignames   = {'Grip Onset (svwostim)(up-0-1000)',...
%     'Grip Onset (svwostim)(up-500-1500)',...
%     'Grip Onset (svwostim)(up-1000-2000)',...
%     'Grip Onset (svwostim)(up-1500-2500)',...
%     'Grip Onset (svwostim)(up-2000-3000)',...
%     'Grip Onset (svwostim)(up-2500-3500)',...
%     'Grip Onset (svwostim)(up-3000-4000)'};

% Trignames   = {'Grip Onset (svwostim)(all-0-1000)',...
%     'Grip Onset (svwostim)(all-500-1500)',...
%     'Grip Onset (svwostim)(all-1000-2000)',...
%     'Grip Onset (svwostim)(all-1500-2500)',...
%     'Grip Onset (svwostim)(all-2000-3000)',...
%     'Grip Onset (svwostim)(all-2500-3500)',...
%     'Grip Onset (svwostim)(all-3000-4000)'};

EMGnames   = {'FDI-subsample',...%
    '2DI-subsample',...
    '3DI-subsample',...
    '4DI-subsample',...
    'ADP-subsample',...
    'AbPB-subsample',...
    'AbDM-subsample',...
    'FDS-subsample',...
    'FDPr-subsample',...
    'FDPu-subsample',...
    'PL-subsample',...
    'FCR-subsample',...
    'FCU-subsample',...
    'AbPL-subsample',...
    'ED23-subsample',...
    'EDC-subsample',...
    'ECR-subsample',...
    'ECU-subsample',...
    'BRD-subsample',...
    'Biceps-subsample',...
    'Triceps-subsample'};



nExp    = length(Expnames);
nEMG    = length(EMGnames);
nTrig   = length(Trignames);

for iExp    = 1:nExp
    try
    Expname     = Expnames{iExp};
    
    fig = open('A4.fig');
    set(fig,'Name',Expname,...
        'FileName',Expname)
    for iEMG   = 1:nEMG
        EMGname     = EMGnames{iEMG};
        jj  = 0;
        for iTrig   = 1:nTrig
            Trigname    = Trignames{iTrig};
            filename    = fullfile(rootpath,[Expname,'_',fieldname,'_',EMGname,'_',Trigname]);
%             keyboard
            s   = load(filename);
            if(s.cl.seg_tot>20)
                jj   = jj + 1;
                Depth(jj)   = (iTrig-1)*ddepth;
                coh(jj,:)     = s.f.coh;
                PSD11(jj,:)   = s.f.PSD11;
                PSD22(jj,:)   = s.f.PSD22;
            end
        end
        PSD11(:,1)  = 0;
        PSD22(:,1)  = 0;
        
        freq    = s.f.freq(:);
%         nDepth  = nTrig;
%         Depth   = ([1:nDepth]-1)*ddepth;

        if(iEMG==1)
            h   = subplot(11,4,1);
            pcolor(freq,Depth,PSD11); shading flat
            set(h,'YDir','Reverse',...
                'YLim',DOI,...
                'XLim',FOI)
            title(h,fieldname)
            
            h   = subplot(11,4,2);
            title({rootpath;Expname;datestr(now)})
        end

        h   = subplot(11,4,iEMG*2+1);
        pcolor(freq,Depth,PSD22); shading flat
        set(h,'YDir','Reverse',...
                'YLim',DOI,...
                'XLim',FOI)
        title(EMGname)

        h   = subplot(11,4,iEMG*2+2);
        pcolor(freq,Depth,coh); shading flat
        set(gca,'clim',[cohcl(0.05,50) 0.3],...
            'YDir','Reverse',...
                'YLim',DOI,...
                'XLim',FOI)
        colormap(tmap2)
        title('coh')
    end
%     print(fig)
%     close(fig)
    disp([Expname, ' was printed out'])
    catch
        Expname     = Expnames{iExp};
        disp(['error occured in',Expname])
    end
end





