
% rootpath    = 'L:\tkitom\data\tcohsurvey\080619_EndHold';
% rootpath    = 'L:\tkitom\data\tcohsurvey\080619_GripOn';
% rootpath    = 'L:\tkitom\data\tcohsurvey\080619_PreGripOn';

% rootpath        = 'tcohsurvey\080624_GripOn';
% rootpath    = 'L:\tkitom\data\tcohsurvey\080624_EndHold';

% rootpath    = 'L:\tkitom\data\tcohsurvey\080711_GripOn';
% rootpath    = 'L:\tkitom\data\tcohsurvey\080711_EndHold';

% rootpath        = fullfile(datapath,rootpath);
rootpath        = uigetdir(fullfile(datapath,'tcohsurvey'));

% Expnames    = {'EitoT001';...
%     'EitoT002';...    'EitoT003';...
%     'EitoT004';...
%     'EitoT005';...
%     'EitoT006';...
%     'EitoT007';...
%     'EitoT008';...
%     'EitoT009';...
%     'EitoT010';...
%     'EitoT011';...
%     'EitoT012';...
%     'EitoT013';...
%     'EitoT014';...
%     'EitoT015';...
%     'EitoT016';...
%     'EitoT017';...
%     'EitoT018';...
%     'EitoT019';...    'EitoT020';...
%     'EitoT021';...    'EitoT022';...
%     'EitoT023';...
%     'EitoT024';...
%     'EitoT025';...
%     'EitoT026';...
%     'EitoT027';...
%     'EitoC013';...
%     'EitoC014';...
%     'EitoC015';...
%     'EitoC016';...
%     'EitoC017';...
%     'EitoC018';...
%     'EitoC019';...
%     'EitoC020';...
%     'EitoC021'};

% Expnames    = {'EitoC034',...
%     'EitoC035',...
%     'EitoC036'};

% Expnames    = {'EitoT009'};
% keyboard
Expnames    = {'EitoT001';...
    'EitoT002';...    'EitoT003';...
    'EitoT004';...
    'EitoT005';...
    'EitoT006';...
    'EitoT007';...
    'EitoT008';...
    'EitoT009';...
    'EitoT010';...
    'EitoT011';...
    'EitoT012';...
    'EitoT013';...
    'EitoT014';...
    'EitoT015';...
    'EitoT016';...
    'EitoT017';...
    'EitoT018';...
    'EitoT019';...    'EitoT020';...
    'EitoT021';...    'EitoT022';...
    'EitoT023';...
    'EitoT024';...
    'EitoT025';...
    'EitoT026';...
    'EitoT027';...
    'EitoC013';...
    'EitoC014';...
    'EitoC015';...
    'EitoC016';...
    'EitoC017';...
    'EitoC018';...
    'EitoC019';...
    'EitoC020';...
    'EitoC021';...
    'EitoC022';...
    'EitoC023';...
    'EitoC024';...
    'EitoC025';...
    'EitoC026';...
    'EitoC027';...
    'EitoC028';...
    'EitoC029';...
    'EitoC030';...
    'EitoC031';...
    'EitoC032';...
    'EitoC033';...
    'EitoC034';...
    'EitoC035';...
    'EitoC036';...
    'EitoC037';...
    'EitoC038';...
    'EitoC039';...
    'EitoC040';...
    'EitoC041';...
    'EitoC042';...
    'EitoC043';...
    'EitoC044';...
    'EitoC045';...
    'EitoC046';...
    'EitoC047';...
    'EitoC048';...
    'EitoC049';...
    'EitoC050';...
    'EitoC051';...
    'EitoC052';...
    'EitoC053';...
    'EitoC054';...
    'EitoC055';...
    'EitoC056';...
    'EitoC057';...
    'EitoC058';...
    'EitoC059';...
    'EitoC060';...
    'EitoC061';...
    'EitoC062';...
    'EitoC063';...
    'EitoC064';...
    'EitoC065';...
    'EitoC066';...
    'EitoC067';...
    'EitoC068';...
    'EitoC069';...
    'EitoC070'};

Expnames    = uiselect(Expnames);

fieldname   = 'Field 1-subsample';
% fieldname   = 'Field 2-subsample';
% fieldname   = 'Field 3-subsample';

EMGnames   = {'FDI-subsample',...%
    '2DI-subsample',...
    '3DI-subsample',...
    '4DI-subsample',...
    'ADP-subsample',...
    'AbPB-subsample',...
    'AbDM-subsample',...
    'FDS-subsample',...
    'FDPr-subsample',...
    'FDPu-subsample',...
    'PL-subsample',...
    'FCR-subsample',...
    'FCU-subsample',...
    'AbPL-subsample',...
    'ED23-subsample',...
    'EDC-subsample',...
    'ECR-subsample',...
    'ECU-subsample',...
    'BRD-subsample',...
    'Biceps-subsample',...
    'Triceps-subsample'};



nExp    = length(Expnames);
nEMG    = length(EMGnames);

for iExp    = 1:nExp
    try
    Expname     = Expnames{iExp};
    
    fig = open('A4.fig');
    set(fig,'Name',Expname,...
        'FileName',Expname)
    for iEMG   = 1:nEMG
        EMGname     = EMGnames{iEMG};
        filename    = fullfile(rootpath,[Expname,'_',fieldname,'_',EMGname]);
        
        s   = load(filename);
        coh     = s.f.coh;
        PSD11   = s.f.PSD11;
        PSD22   = s.f.PSD22;
        PSD11(:,1)  = 0;
        PSD22(:,1)  = 0;
        
        freq    = s.f.freq(1,:);
        seg_tot = size(s.f.freq,1);

        if(iEMG==1)
            h   = subplot(11,4,1);
            pcolor(freq,[1:seg_tot],PSD11); shading flat
            set(h,'YDir','Reverse')
            title(h,fieldname)
            
            h   = subplot(11,4,2);
            title({rootpath;Expname;datestr(now)})
        end

        h   = subplot(11,4,iEMG*2+1);
        pcolor(freq,[1:seg_tot],PSD22); shading flat
        set(h,'YDir','Reverse')
        title(EMGname)

        h   = subplot(11,4,iEMG*2+2);
        pcolor(freq,[1:seg_tot],coh); shading flat
        set(gca,'clim',[s.cl.ch_c95 0.25],...
            'YDir','Reverse')
        colormap(tmap2)
        title('coh')
    end
%     print(fig)
try
        saveas(fig,fullfile(datapath,'figures','tcohsurvey',Expname),'jpg')
        saveas(fig,fullfile(datapath,'figures','tcohsurvey',Expname),'pdf')
        saveas(fig,fullfile(datapath,'figures','tcohsurvey',Expname),'fig')
        close(fig)
    disp([Expname, ' was printed out'])
catch
    keyboard
    iExp    = iExp-1;
end
    catch
        Expname     = Expnames{iExp};
        disp(['error occured in',Expname])
    end
end





