function tcohtrig_print
% rootpath    = 'L:\tkitom\data\tcohsurvey\080619_EndHold';
% rootpath    = 'L:\tkitom\data\tcohsurvey\080619_GripOn';
% rootpath    = 'L:\tkitom\data\tcohsurvey\080619_PreGripOn';
warning('off')
rootpath    = fullfile(datapath,'tcohtrig','080717GripOn');
FOI         = [0 100];
% 
% Expnames    = {'EitoT00401MSf',...
%     'EitoT00801MSf',...
%     'EitoT00802MSf',...
%     'EitoT00901MSf',...
%     'EitoT00902MSf',...
%     'EitoT01101MSf',...
%     'EitoT01201MSf',...
%     'EitoT01202MSf',...
%     'EitoT01301MSf',...
%     'EitoT01302MSf',...
%     'EitoT01303MSf',...
%     'EitoT01304MSf',...
%     'EitoT01401MSf',...
%     'EitoT01601MSf',...
%     'EitoT02101MSf',...
%     'EitoT02401MSf',...
%     'EitoT02402MSf',...
%     'EitoT02601MSf',...
%     'EitoT02701MSf'};
Expnames    = {'EitoT01401MSf',...
    'EitoT02601MSf',...
    'EitoT02701MSf'};

fieldname   = 'Field 1-subsample';

EMGnames   = {'FDI-subsample',...%
    '2DI-subsample',...
    '3DI-subsample',...
    '4DI-subsample',...
    'ADP-subsample',...
    'AbPB-subsample',...
    'AbDM-subsample',...
    'FDS-subsample',...
    'FDPr-subsample',...
    'FDPu-subsample',...
    'PL-subsample',...
    'FCR-subsample',...
    'FCU-subsample',...
    'AbPL-subsample',...
    'ED23-subsample',...
    'EDC-subsample',...
    'ECR-subsample',...
    'ECU-subsample',...
    'BRD-subsample',...
    'Biceps-subsample',...
    'Triceps-subsample'};



nExp    = length(Expnames);
nEMG    = length(EMGnames);
nerror  = 0;

for iExp    = 1:nExp
    try
    Expname     = Expnames{iExp};
    
    fig = open('A4.fig');
    set(fig,'Name',Expname,...
        'FileName',Expname)
    for iEMG   = 1:nEMG
        EMGname     = EMGnames{iEMG};
        filename    = fullfile(rootpath,[Expname,'_',fieldname,'_',EMGname]);
        
        s   = load(filename);
        coh     = s.f.coh;
        PSD11   = s.f.PSD11;
        PSD22   = s.f.PSD22;
        PSD11(1)  = 0;
        PSD22(1)  = 0;
        
        freq    = s.f.freq(1,:);
        seg_tot = size(s.f.freq,1);

        if(iEMG==1)
            h   = subplot(11,4,1);
            plot(freq,PSD11,'-k')
            set(h,'XLim',FOI);
            title(h,fieldname)
            hpower(nEMG+1)    = h;
            
            h   = subplot(11,4,2);
            title({rootpath;Expname;datestr(now)})
        end

        h   = subplot(11,4,iEMG*2+1);
        plot(freq,PSD22,'-k')
        set(h,'XLim',FOI);
%         ylabel('power')
        title(EMGname)
        hpower(iEMG)    = h;

        h   = subplot(11,4,iEMG*2+2);
        plot(freq,coh,'-k')
        hold on;
        plot(FOI,[s.cl.ch_c95 s.cl.ch_c95],'--k');
        set(h,'XLim',FOI,...
            'Ylim',[0 0.2])
        ylabel('coh')
        title(['n= ',num2str(s.cl.seg_tot)])
        hcoh(iEMG)    = h;
    end
%     linkaxes(hpower,'xy');
%     linkaxes(hcoh,'xy');
    %     print(fig)
%     close(fig)
    disp([Expname, ' was printed out'])
    catch
        Expname     = Expnames{iExp};
        disp(['error occured in',Expname])
        nerror  = nerror+1;
        a(nerror)   = lasterror;
    end
end
warning('on')
keyboard




