function tcohtrig_btc(Pathname)

Datapath    = matpath;
rootpath    = fullfile(datapath,'tcohtrig');
Outputpath     = fullfile(rootpath,Pathname);
mkdir(Outputpath);

TimeWindow  = [0 0.512];
nfftPoints  = 128;  % for compiled analyses
maxtrial    = 100;

trigfile   = 'Grip Onset (svwostim)';

% Expnames	={'EitoT00401MSf',...
%     'EitoT00801MSf',...
%     'EitoT00802MSf',...
%     'EitoT00901MSf',...
%     'EitoT00902MSf',...
%     'EitoT01101MSf',...
%     'EitoT01201MSf',...
%     'EitoT01202MSf',...
%     'EitoT01301MSf',...
%     'EitoT01302MSf',...
%     'EitoT01303MSf',...
%     'EitoT01304MSf',...
%     'EitoT01401MSf',...
%     'EitoT01601MSf',...
%     'EitoT02101MSf',...
%     'EitoT02401MSf',...
%     'EitoT02402MSf',...
%     'EitoT02601MSf',...
%     'EitoT02701MSf'};
Expnames	={'EitoT01401MSf',...
    'EitoT02601MSf',...
    'EitoT02701MSf'};
% Expnames	={'EitoT00401MSf'};

channames = {'Field 1-subsample','FDI-subsample';...
    'Field 1-subsample','ADP-subsample';...
    'Field 1-subsample','3DI-subsample';...
    'Field 1-subsample','2DI-subsample';...
    'Field 1-subsample','AbPB-subsample';...
    'Field 1-subsample','BRD-subsample';...
    'Field 1-subsample','ED23-subsample';...
    'Field 1-subsample','ECR-subsample';...
    'Field 1-subsample','EDC-subsample';...
    'Field 1-subsample','ECU-subsample';...
    'Field 1-subsample','AbPL-subsample';...
    'Field 1-subsample','4DI-subsample';...
    'Field 1-subsample','AbDM-subsample';...
    'Field 1-subsample','FCR-subsample';...
    'Field 1-subsample','FDS-subsample';...
    'Field 1-subsample','FDPr-subsample';...
    'Field 1-subsample','FDPu-subsample';...
    'Field 1-subsample','FCU-subsample';...
    'Field 1-subsample','PL-subsample';...
    'Field 1-subsample','Biceps-subsample';...
    'Field 1-subsample','Triceps-subsample'};
% channames = {'Field 1-subsample','FDI-subsample'};
    
nExp    = length(Expnames);
nchan    = size(channames,1);

for iExp = 1:nExp
    Expname = Expnames{iExp};
    
    
    trig    = load(fullfile(Datapath,Expname,trigfile));
    disp([Expname,'(',num2str(iExp),'/',num2str(nExp),') '])
    
    for ichan    = 1:nchan
        try
        Reffile = channames{ichan,1};
        Tarfile = channames{ichan,2};
        Outputfile  = fullfile(Outputpath,[Expname,'_',Reffile,'_',Tarfile]);
        
        Ref     = load(fullfile(Datapath,Expname,Reffile));
        Tar     = load(fullfile(Datapath,Expname,Tarfile));
        
        [f,cl]  = tcohtrig(Ref, Tar, trig,  TimeWindow, nfftPoints, maxtrial);

        
        save(Outputfile,'f','cl')
        disp([' L--(',num2str(ichan),'/',num2str(nchan),') ',Outputfile,' was created.'])
        catch
            disp([' L--(',num2str(ichan),'/',num2str(nchan),') ***** Error occured in ',Outputfile,'.'])
            
        end
    end
end