function tcohsurvey_btc(Pathname)

Datapath    = uigetdir(matpath);
rootpath    = fullfile(datapath,'tcohsurvey');
Outputpath     = fullfile(rootpath,Pathname);
mkdir(Outputpath);
% 

% Expnames    = {'EitoT001';...
%     'EitoT002';...    'EitoT003';...
%     'EitoT004';...
%     'EitoT005';...
%     'EitoT006';...
%     'EitoT007';...
%     'EitoT008';...
%     'EitoT009';...
%     'EitoT010';...
%     'EitoT011';...
%     'EitoT012';...
%     'EitoT013';...
%     'EitoT014';...
%     'EitoT015';...
%     'EitoT016';...
%     'EitoT017';...
%     'EitoT018';...
%     'EitoT019';...    'EitoT020';...
%     'EitoT021';...    'EitoT022';...
%     'EitoT023';...
%     'EitoT024';...
%     'EitoT025';...
%     'EitoT026';...
%     'EitoT027';...
%     'EitoC013';...
%     'EitoC014';...
%     'EitoC015';...
%     'EitoC016',...
%     'EitoC017',...
%     'EitoC018',...
%     'EitoC019',...
%     'EitoC020',...
%     'EitoC021'};

% Expnames    = {'EitoC035',...
%     'EitoC036',...
%     'EitoC037',...
%     'EitoC038',...
%     'EitoC039',...
%     'EitoC040',...
%     'EitoC041',...
%     'EitoC042',...
%     'EitoC043',...
%     'EitoC044',...
%     'EitoC045',...
%     'EitoC046',...
%     'EitoC047',...
%     'EitoC048',...
%     'EitoC049',...
%     'EitoC050',...
%     'EitoC051',...
%     'EitoC052',...
%     'EitoC053',...
%     'EitoC054',...
%     'EitoC055',...
%     'EitoC056',...
%     'EitoC057',...
%     'EitoC058'};
Expnames    = dir(Datapath);
% keyboard
Expnames    = {Expnames([Expnames.isdir]==1).name};
Expnames   = uiselect(Expnames);


% trigfile    = 'Grip Onset (svwostim)';
trigfile    = 'CentT Off (svwostim)';


channames = {'Field 1-subsample','FDI-subsample';...
    'Field 1-subsample','ADP-subsample';...
    'Field 1-subsample','3DI-subsample';...
    'Field 1-subsample','2DI-subsample';...
    'Field 1-subsample','AbPB-subsample';...
    'Field 1-subsample','BRD-subsample';...
    'Field 1-subsample','ED23-subsample';...
    'Field 1-subsample','ECR-subsample';...
    'Field 1-subsample','EDC-subsample';...
    'Field 1-subsample','ECU-subsample';...
    'Field 1-subsample','AbPL-subsample';...
    'Field 1-subsample','4DI-subsample';...
    'Field 1-subsample','AbDM-subsample';...
    'Field 1-subsample','FCR-subsample';...
    'Field 1-subsample','FDS-subsample';...
    'Field 1-subsample','FDPr-subsample';...
    'Field 1-subsample','FDPu-subsample';...
    'Field 1-subsample','FCU-subsample';...
    'Field 1-subsample','PL-subsample';...
    'Field 1-subsample','Biceps-subsample';...
    'Field 1-subsample','Triceps-subsample'};


% channames = {'Field 1-subsample','FDI-subsample';...
%     'Field 1-subsample','ADP-subsample';...
%     'Field 1-subsample','3DI-subsample';...
%     'Field 1-subsample','2DI-subsample';...
%     'Field 1-subsample','AbPB-subsample';...
%     'Field 1-subsample','BRD-subsample';...
%     'Field 1-subsample','ED23-subsample';...
%     'Field 1-subsample','ECR-subsample';...
%     'Field 1-subsample','EDC-subsample';...
%     'Field 1-subsample','ECU-subsample';...
%     'Field 1-subsample','AbPL-subsample';...
%     'Field 1-subsample','4DI-subsample';...
%     'Field 1-subsample','AbDM-subsample';...
%     'Field 1-subsample','FCR-subsample';...
%     'Field 1-subsample','FDS-subsample';...
%     'Field 1-subsample','FDPr-subsample';...
%     'Field 1-subsample','FDPu-subsample';...
%     'Field 1-subsample','FCU-subsample';...
%     'Field 1-subsample','PL-subsample';...
%     'Field 1-subsample','Biceps-subsample';...
%     'Field 1-subsample','Triceps-subsample';...
%     'Field 2-subsample','FDI-subsample';...
%     'Field 2-subsample','ADP-subsample';...
%     'Field 2-subsample','3DI-subsample';...
%     'Field 2-subsample','2DI-subsample';...
%     'Field 2-subsample','AbPB-subsample';...
%     'Field 2-subsample','BRD-subsample';...
%     'Field 2-subsample','ED23-subsample';...
%     'Field 2-subsample','ECR-subsample';...
%     'Field 2-subsample','EDC-subsample';...
%     'Field 2-subsample','ECU-subsample';...
%     'Field 2-subsample','AbPL-subsample';...
%     'Field 2-subsample','4DI-subsample';...
%     'Field 2-subsample','AbDM-subsample';...
%     'Field 2-subsample','FCR-subsample';...
%     'Field 2-subsample','FDS-subsample';...
%     'Field 2-subsample','FDPr-subsample';...
%     'Field 2-subsample','FDPu-subsample';...
%     'Field 2-subsample','FCU-subsample';...
%     'Field 2-subsample','PL-subsample';...
%     'Field 2-subsample','Biceps-subsample';...
%     'Field 2-subsample','Triceps-subsample';...
%     'Field 3-subsample','FDI-subsample';...
%     'Field 3-subsample','ADP-subsample';...
%     'Field 3-subsample','3DI-subsample';...
%     'Field 3-subsample','2DI-subsample';...
%     'Field 3-subsample','AbPB-subsample';...
%     'Field 3-subsample','BRD-subsample';...
%     'Field 3-subsample','ED23-subsample';...
%     'Field 3-subsample','ECR-subsample';...
%     'Field 3-subsample','EDC-subsample';...
%     'Field 3-subsample','ECU-subsample';...
%     'Field 3-subsample','AbPL-subsample';...
%     'Field 3-subsample','4DI-subsample';...
%     'Field 3-subsample','AbDM-subsample';...
%     'Field 3-subsample','FCR-subsample';...
%     'Field 3-subsample','FDS-subsample';...
%     'Field 3-subsample','FDPr-subsample';...
%     'Field 3-subsample','FDPu-subsample';...
%     'Field 3-subsample','FCU-subsample';...
%     'Field 3-subsample','PL-subsample';...
%     'Field 3-subsample','Biceps-subsample';...
%     'Field 3-subsample','Triceps-subsample'};


nExp    = length(Expnames);
nchan    = size(channames,1);

for iExp = 1:nExp
    Expname = Expnames{iExp};
    
    
    trig    = load(fullfile(Datapath,Expname,trigfile));
    disp([Expname,'(',num2str(iExp),'/',num2str(nExp),') '])
    
    for ichan    = 1:nchan
        try
        Reffile = channames{ichan,1};
        Tarfile = channames{ichan,2};
        Outputfile  = fullfile(Outputpath,[Expname,'_',Reffile,'_',Tarfile]);
        
        Ref     = load(fullfile(Datapath,Expname,Reffile));
        Tar     = load(fullfile(Datapath,Expname,Tarfile));
        
%         [f,cl]  = tcohsurvey(Ref, Tar, trig,  [-0.512 0.512], 128, 100);
%         [f,cl]  = tcohsurvey(Ref, Tar, trig,  [-1.024 1.024], 512, 100);
        [f,cl]  = tcohsurvey(Ref, Tar, trig,  [0 0.512], 128, 100);
%         [f,cl]  = tcohsurvey(Ref, Tar, trig,  [-0.512 0], 128, 100);
%         [f,cl]  = tcohsurvey(Ref, Tar, trig,  [-2.048 3.072], 128, 100);
        
        save(Outputfile,'f','cl')
        disp([' L--(',num2str(ichan),'/',num2str(nchan),') ',Outputfile,' was created.'])
        catch
            disp([' L--(',num2str(ichan),'/',num2str(nchan),') ***** Error occured in ',Outputfile,'.'])
            
        end
    end
end