function trace2wcoh_btc


% --------------------------
% Set parameters

% ExpSets	={{'AobaT00101'},...
%     {'AobaT00201','AobaT00202'},...
%     {'AobaT00203'},...
%     {'AobaT00301'},...
%     {'AobaT00302','AobaT00306'},...
%     {'AobaT00304','AobaT00305'},...
%     {'AobaT00403','AobaT00404'},...
%     {'AobaT00503'},...
%     {'AobaT00602'},...
%     {'AobaT00603'},...
%     {'AobaT00607','AobaT00608'},...
%     {'AobaT00902'},...
%     {'AobaT00903','AobaT00914'},...
%     {'AobaT00907'},...
%     {'AobaT01101'},...
%     {'AobaT01105','AobaT01106'},...
%     {'AobaT01108','AobaT01112'},...
%     {'AobaT01114','AobaT01114'},...
%     {'AobaT01702','AobaT01710'},...
%     {'AobaT01712'},...
%     {'AobaT01801'},...
%     {'AobaT01802'},...
%     {'AobaT01804'},...
%     {'AobaT01901'},...
%     {'AobaT01904','AobaT01905'},...
%     {'AobaT01906','AobaT01907'},...
%     {'AobaT02302'},...
%     {'AobaT02401','AobaT02402'},...
%     {'AobaT02403'},...
%     {'AobaT02405','AobaT02407'}};
% ExpSets	={{'AobaT02405','AobaT02407'}};
% 
% % ExpSets	={{'AobaT02405','AobaT02407'}};
% 
% Reffile     = 'STA (Grip Onset (success valid), Non-filtered-subsample(uV)).mat';

%   {ExpSet                     Reffile                                                                 Tarfile;}                                     
% {'AobaT00101'}              'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'   'STA (Release Onset (success valid), FDI-subsample(uV)).mat';...{'AobaT00101'}           'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'   'STA (Release Onset (success valid), BRD-subsample(uV)).mat';...
%     {'AobaT00201','AobaT00202'} 'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), AbDM-subsample(uV)).mat';...
Ana = {{'AobaT00201','AobaT00202'} 'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), ADP-subsample(uV)).mat';...
    {'AobaT00201','AobaT00202'} 'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), BRD-subsample(uV)).mat';...
    {'AobaT00201','AobaT00202'} 'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), FDPr-subsample(uV)).mat';...
    {'AobaT00203'}              'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), AbDM-subsample(uV)).mat';...
    {'AobaT00203'}              'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), AbPB-subsample(uV)).mat';...
    {'AobaT00203'}              'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), ADP-subsample(uV)).mat';...
    {'AobaT00203'}              'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), BB-subsample(uV)).mat';...
    {'AobaT00203'}              'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), BRD-subsample(uV)).mat';...
    {'AobaT00203'}              'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), ECU-subsample(uV)).mat';...
    {'AobaT00203'}              'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), ED23-subsample(uV)).mat';...
    {'AobaT00203'}              'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), FDI-subsample(uV)).mat';...
    {'AobaT00203'}              'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), FDPr-subsample(uV)).mat';...
    {'AobaT00301'}              'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), BB-subsample(uV)).mat';...
    {'AobaT00301'}              'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), PL-subsample(uV)).mat';...
    {'AobaT00301'}              'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), PT-subsample(uV)).mat';...
    {'AobaT00302','AobaT00306'}	'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), AbPB-subsample(uV)).mat';...
    {'AobaT00302','AobaT00306'}	'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), ADP-subsample(uV)).mat';...
    {'AobaT00302','AobaT00306'}	'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), FDI-subsample(uV)).mat';...
    {'AobaT00302','AobaT00306'}	'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), FDPr-subsample(uV)).mat';...
    {'AobaT00302','AobaT00306'}	'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), FDS-subsample(uV)).mat';...
    {'AobaT00302','AobaT00306'}	'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), PL-subsample(uV)).mat';...
    {'AobaT00903','AobaT00914'} 'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), AbPB-subsample(uV)).mat';...
    {'AobaT00903','AobaT00914'} 'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), BRD-subsample(uV)).mat';...
    {'AobaT00903','AobaT00914'} 'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), FDS-subsample(uV)).mat';...
    {'AobaT00903','AobaT00914'} 'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), PT-subsample(uV)).mat';...
    {'AobaT00907'}              'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), ADP-subsample(uV)).mat';...
    {'AobaT00907'}              'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), BRD-subsample(uV)).mat';...
    {'AobaT01101'}              'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), AbPB-subsample(uV)).mat';...
    {'AobaT01105','AobaT01106'} 'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), AbPB-subsample(uV)).mat';...
    {'AobaT01105','AobaT01106'} 'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), PL-subsample(uV)).mat';...
    {'AobaT01108','AobaT01112'} 'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), AbPB-subsample(uV)).mat';...
    {'AobaT01108','AobaT01112'} 'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), ADP-subsample(uV)).mat';...
    {'AobaT01108','AobaT01112'} 'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), BRD-subsample(uV)).mat';...
    {'AobaT01108','AobaT01112'} 'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), FDI-subsample(uV)).mat';...
    {'AobaT01108','AobaT01112'} 'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), FDPr-subsample(uV)).mat';...
    {'AobaT01108','AobaT01112'} 'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), FDPu-subsample(uV)).mat';...
    {'AobaT01108','AobaT01112'} 'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), FDS-subsample(uV)).mat';...
    {'AobaT01108','AobaT01112'} 'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), PL-subsample(uV)).mat';...
    {'AobaT01114','AobaT01114'} 'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), FCR-subsample(uV)).mat';...
    {'AobaT01114','AobaT01114'} 'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), FCU-subsample(uV)).mat';...
    {'AobaT01114','AobaT01114'} 'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), FDPr-subsample(uV)).mat';...
    {'AobaT01114','AobaT01114'} 'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), PL-subsample(uV)).mat';...
    {'AobaT02401','AobaT02402'} 'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), AbPB-subsample(uV)).mat';...
    {'AobaT02405','AobaT02407'} 'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), AbDM-subsample(uV)).mat';...
    {'AobaT02405','AobaT02407'} 'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), AbPB-subsample(uV)).mat';...
    {'AobaT02405','AobaT02407'} 'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), ADP-subsample(uV)).mat';...
    {'AobaT02405','AobaT02407'} 'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), BRD-subsample(uV)).mat';...
    {'AobaT02405','AobaT02407'} 'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), FCU-subsample(uV)).mat';...
    {'AobaT02405','AobaT02407'} 'STA (Release Onset (success valid), Non-filtered-subsample(uV)).mat'	'STA (Release Onset (success valid), FDPr-subsample(uV)).mat'};


Outputdir   = 'L:\tkitom\data\wcoh\ReleaseOnset(070822)_1-100Hz';
Sourcedir   = 'L:\tkitom\MDAdata\Analyses\STA';

freqVec     = [1.25:1.25:100];   % Hz
sigma       = 0.128;            % sec

% --------------------------


mkdir(Outputdir);
nAna	= size(Ana,1);
% nTarget	= length(Tarfiles);
tic;
for ii=1:nAna
    try
        currExpSet  = Ana{ii,1};
        firstExp	= currExpSet{1};
        nExp        = length(currExpSet);
        Reffile     = Ana{ii,2};
        Tarfile     = Ana{ii,3};



        for jj=1:nExp
            Ref     = load(fullfile(Sourcedir,currExpSet{jj},Reffile));
            if(jj==1)
                RefData	= Ref.TrialData;
                RefName = Ref.TargetName;
                timeVec = Ref.XData;
                Fs      = Ref.SampleRate;
            else
                RefData	= [RefData;Ref.TrialData];
            end
        end
        clear('Ref');pack;

        for jj=1:nExp
            Tar     = load(fullfile(Sourcedir,currExpSet{jj},Tarfile));
            if(jj==1)
                TarData	= Tar.TrialData;
                TarName = Tar.TargetName;
            else
                TarData	= [TarData;Tar.TrialData];
            end
        end
        clear('Tar');pack;
        Outputfile  = (fullfile(Outputdir,[firstExp,'_',RefName,'__',TarName,'.mat']));

        [cxy,txxx,fxxx,px,py,phi]   =trace2wcoh(RefData,TarData,freqVec,Fs,sigma);
        cl.sigma        = sigma;
        cl.seg_tot      = size(RefData,1);
        cl.samp_rate    = Fs;
        cl.ch_c95       = cohcl(0.05,size(RefData,1));
        freq            = freqVec;
        t               = timeVec;

        save(Outputfile,'px','py','cxy','phi','cl','freq','t')

        dispremainhr(ii,nAna,Outputfile);
        
    catch
        currExpSet  = Ana{ii,1};
        firstExp	= currExpSet{1};
        disp(['*** Error occured in ',firstExp])
    end

end

