function trace2wcoh_btc(Outputdir)
% trace2wcoh_btc(Outputdir)
% ex.
% trace2wcoh_btc('071106');

warning('off');
if nargin<1
    error('Outputdir must be specified. (ex.) trace2wcoh_btc(''071106'')');
    %     return;
end



% --------------------------
% Set parameters
%

maxtrials    = 50;


ExpSets	={{'EitoT00407f','EitoT00408f'},...
    {'EitoT00409f'},...
    {'EitoT00410f'},...
    {'EitoT00501f'},...
    {'EitoT00502f'},...
    {'EitoT00504f','EitoT00505f'},...
    {'EitoT00509f'},...
    {'EitoT00510f'},...
    {'EitoT00603f'},...
    {'EitoT00607f','EitoT00608f'},...
    {'EitoT00609f','EitoT00610f'},...
    {'EitoT00612f'},...
    {'EitoT00613f'},...
    {'EitoT00614f'},...
    {'EitoT00702f','EitoT00703f'},...
    {'EitoT00704f','EitoT00705f'},...
    {'EitoT00709f','EitoT00710f'},...
    {'EitoT00712f'},...
    {'EitoT00713f'},...
    {'EitoT00802f'},...
    {'EitoT00805f','EitoT00806f','EitoT00807f'},...
    {'EitoT00808f','EitoT00809f'},...
    {'EitoT00816f','EitoT00817f'},...
    {'EitoT00901f'},...    
    {'EitoT00902f','EitoT00903f'},...
    {'EitoT00904f','EitoT00905f','EitoT00906f','EitoT00907f'},...
    {'EitoT00910f'},...
    {'EitoT01001f'},...
    {'EitoT01003f'},...
    {'EitoT01004f'},...
    {'EitoT01005f'},...
    {'EitoT01006f','EitoT01007f'},...
    {'EitoT01009f','EitoT01010f','EitoT01011f','EitoT01012f'},...
    {'EitoT01013f'},...
    {'EitoT01015f'},...
    {'EitoT01016f'},...
    {'EitoT01101f'},...
    {'EitoT01202f'}};




% Reffile     = 'STA (Grip Onset (success valid), Non-filtered-subsample(uV)).mat';
% Reffile     = 'STA (Grip Onset (success valid)(0-500um), Field 1-subsample).mat';
Reffile     = 'STA (Grip Onset (svwostim), Field 1-subsample(uV)).mat';

Original_Tarfiles	= {'STA (Grip Onset (svwostim), FDI-subsample(uV)).mat',...
    'STA (Grip Onset (svwostim), ADP-subsample(uV)).mat',...
    'STA (Grip Onset (svwostim), 3DI-subsample(uV)).mat',...
    'STA (Grip Onset (svwostim), 2DI-subsample(uV)).mat',...
    'STA (Grip Onset (svwostim), AbPB-subsample(uV)).mat',...
    'STA (Grip Onset (svwostim), BRD-subsample(uV)).mat',...
    'STA (Grip Onset (svwostim), ED23-subsample(uV)).mat',...
    'STA (Grip Onset (svwostim), ECR-subsample(uV)).mat',...
    'STA (Grip Onset (svwostim), EDC-subsample(uV)).mat',...
    'STA (Grip Onset (svwostim), ECU-subsample(uV)).mat',...
    'STA (Grip Onset (svwostim), AbPL-subsample(uV)).mat',...
    'STA (Grip Onset (svwostim), 4DI-subsample(uV)).mat',...
    'STA (Grip Onset (svwostim), AbDM-subsample(uV)).mat',...
    'STA (Grip Onset (svwostim), FCR-subsample(uV)).mat',...
    'STA (Grip Onset (svwostim), FDS-subsample(uV)).mat',...
    'STA (Grip Onset (svwostim), FDPr-subsample(uV)).mat',...
    'STA (Grip Onset (svwostim), FDPu-subsample(uV)).mat',...
    'STA (Grip Onset (svwostim), FCU-subsample(uV)).mat',...
    'STA (Grip Onset (svwostim), PL-subsample(uV)).mat',...
    'STA (Grip Onset (svwostim), Biceps-subsample(uV)).mat',...
    'STA (Grip Onset (svwostim), Triceps-subsample(uV)).mat'};

Outputdir   = fullfile(datapath,'wcoh',Outputdir);
Sourcedir   = fullfile(datapath,'STA');

freqVec     = [1.25:1.25:100];   % Hz
% freqVec     = [2:2:100];   % Hz
sigma       = 0.128;            % sec

% --------------------------

Tarfiles    = uiselect(Original_Tarfiles,1,'対象となるファイルを選択してください。');
uiwait(msgbox(Tarfiles,'確認','modal'));

mkdir(Outputdir);
nExpSet	= length(ExpSets);
% nTarget	= length(Tarfiles);

for ii=1:nExpSet
    try
        currExpSet  = ExpSets{ii};
        firstExp	= currExpSet{1};
        nExp        = length(currExpSet);

        disp([num2str(ii),'/',num2str(nExpSet),' == ',firstExp])

        %     Tarfiles    = uiselect(Original_Tarfiles,1,firstExp);
        %     uiwait(msgbox(Tarfiles,firstExp,'modal'));

        nTarget	= length(Tarfiles);

        if(nTarget < 1)
            continue;
        end

        for jj=1:nExp
            Ref     = load(fullfile(Sourcedir,currExpSet{jj},Reffile));
            if(jj==1)
                RefData	= Ref.TrialData;
                RefName = Ref.TargetName;
                timeVec = Ref.XData;
                Fs      = Ref.SampleRate;
            else
                RefData	= [RefData;Ref.TrialData];
            end
        end
        ntrials = size(RefData,1);
        rand('state',0) % ランダムで選ぶけど、いつも同じセットが出るようにしているということ
        randind     = randperm(ntrials);

        if ntrials  > maxtrials
            RefData = RefData(randind(1:maxtrials),:);
        end

        clear('Ref');pack;

        for kk =1:nTarget
            Tarfile = Tarfiles{kk};
            for jj=1:nExp
                Tar     = load(fullfile(Sourcedir,currExpSet{jj},Tarfile));
                if(jj==1)
                    TarData	= Tar.TrialData;
                    TarName = Tar.TargetName;
                else
                    TarData	= [TarData;Tar.TrialData];
                end
            end

            if ntrials  > maxtrials
                TarData = TarData(randind(1:maxtrials),:);
            end

            clear('Tar');pack;
            Outputfile  = (fullfile(Outputdir,[firstExp,'_',RefName,'__',TarName,'.mat']));


            [cxy,txxx,fxxx,px,py,pxy,phi]   =trace2wcoh(RefData,TarData,freqVec,Fs,sigma);
            cl.sigma        = sigma;
            cl.seg_tot      = size(RefData,1);
            cl.samp_rate    = Fs;
            cl.ch_c95       = cohcl(0.05,size(RefData,1));
            freq            = freqVec;
            t               = timeVec;

            save(Outputfile,'px','py','pxy','cxy','phi','cl','freq','t')

            disp(['   ',num2str(kk),'/',num2str(nTarget),' -> ',Outputfile])
        end
    catch
        currExpSet  = ExpSets{ii};
        firstExp	= currExpSet{1};
        disp(['*** Error occured in ',firstExp])
    end

end

warning('on')
