function y  = uichoice(x,str)
% selectedlist  = uiselect(list,title,default_answer);
%       list            must be cell array
%       title           string
%       default_answer  cell array or string
%
%       selectedlist    cell array or empty
%   bug: 同じ名前のものがあると右boxに移動したときに同じものとして認識される。indexbaseの管理が必要
%
%       081012  implemented default_answer

if nargin < 2
    str = 'uichoice';
end
isnumeric_flag  = false;
if(~iscell(x))
    if(isnumeric(x))
        x   = num2cellstr(x);
        isnumeric_flag  = true;
    elseif(ischar(x))
        x   = {x};
    end
end

fig =figure('MenuBar','none',...
    'Name',str,...
    'NumberTitle','off',...
    'PaperUnits', 'centimeters',...
    'PaperOrientation','landscape',...
    'PaperPosition', [0.881189 0.634517 27.9151 19.715],...
    'PaperPositionMode','manual',...
    'Position',[500 188 392 653],...
    'Tag','uichoice',...
    'Toolbar','none');


h.listbox     = uicontrol(fig,'BackgroundColor',[1 1 1],...
    'Max',100,...
    'Min',1,...
    'String',x,...
    'Style','listbox',...
    'Tag','uichoice_listbox',...
    'Units' , 'normalized',...
    'value' , [],...
    'Position' , [0.13 0.11 0.74 0.815]);

h.ok        = uicontrol(fig,'BackgroundColor',get(fig,'Color'),...
    'Callback','set(gcf,''UserData'',true);uiresume;',...
    'Style','Pushbutton',...
    'Units' , 'normalized',...
    'Position' , [0.21 0.02 0.24 0.05],...
    'String','OK');

h.cancel    = uicontrol(fig,'BackgroundColor',get(fig,'Color'),...
    'Callback','set(gcf,''UserData'',false);uiresume;',...
    'Style','Pushbutton',...
    'Units' , 'normalized',...
    'Position' , [0.55 0.02 0.24 0.05],...
    'String','Cancel');

uiwait;

yn  = get(fig,'UserData');

if(yn)
    ind = get(h.listbox,'Value');
    if(isempty(ind))
        y   = [];
    else
    y   = x{ind};
    end
else
    y   = [];
end

if(isnumeric_flag)
    y   = str2double(y);
end

close(fig)


