function viewcohtrig_btc

s.rootpath    = 'L:\tkitom\data\tcohtrig';
% temp        = dir(s.rootpath);
% 
% s.parentpath  = {};
% jj          = 1;
% for ii=1:length(temp)
%     if(temp(ii).isdir==1)
%         s.parentpath{jj}  = temp(ii).name;
%         jj=jj+1;
%     end
% end
% s.parentpath  = s.parentpath(3:length(s.parentpath));
s.parentpath    = s.rootpath;
% s.selecpath   = [];
s.filenames     = [];
s.selectedfile  = [];


fig   =figure('Name','T-controller',...
   'NumberTitle','off',...
   'MenuBar','none',...
   'PaperOrientation','portrait',...
   'PaperPosition',[-2 4.91751 26.4382 19.8287],...%[-2.72314 4.91751 26.4382 19.8287]
   'PaperPositionMode','manual',...
   'PaperType','A4',...
   'Pointer','arrow',...
   'Resize','on',...
   'Units','pixels',...
   'UserData',[],...
   'Position',[247    22   448   903]);%[-922 37 448 903]
s.viewerfig     = figure('Name','T-viwer',...
        'Numbertitle','off',...
        'PaperUnits' ,'centimeters',...
        'PaperOrientation' , 'portrait',...
        'PaperPosition' , [-2.08175 -1.12758 33.8409 23.2392],...
        'PaperPositionMode' , 'manual',...
        'PaperType','A4',...
        'Units' , 'pixels',...
        'Position' , [812    45   749   765],...
        'ToolBar' , 'figure');
% h1  = uicontrol('BackgroundColor',[1 1 1],...
%    'Style','listbox',...
%    'HorizontalAlignment','center',...
%    'Units','normalized',...
%    'Position',[0.04 0.16 0.4 0.8],...
%    'Tag','pathList',...
%    'Max',1,...
%    'Min',0,...
%    'String',s.parentpath,...
%    'Callback','s=get(gcf,''UserData'');ind = get(gco,''Value''); s.selecpath   = s.parentpath{ind}; temp    = what([s.rootpath,''\\'',s.selecpath]);s.filenames   = temp.mat; set(s.h.filelist,''String'',s.filenames);set(gcf,''UserData'',s)');

h1  = uicontrol(fig,'BackgroundColor',[1 1 1],...
   'Style','listbox',...
   'HorizontalAlignment','center',...
   'Units','normalized',...
   'Position',[0.05 0.05 0.92 0.77],...
   'Tag','fileList',...
   'Max',0,...
   'Min',1,...
   'String','',...
   'Callback','s=get(gcf,''UserData'');ind = get(gco,''Value''); filenames   = get(gco,''String'');s.selectedfile =filenames{ind}; triggerind = get(s.h.settrigger,''Value''); triggernames   = get(s.h.settrigger,''String'');s.selectedtrigger =triggernames{triggerind};viewcohtrig(s.viewerfig,[s.parentpath,''\'',s.selectedfile],s.selectedtrigger);set(gcf,''UserData'',s)');


uicontrol(fig,'BackgroundColor',get(fig,'Color'),...
   'Style','pushbutton',...
   'Callback','s=get(gcf,''UserData'');s.parentpath=uigetdir(s.parentpath);temp    = what(s.parentpath);s.filenames   = sort(temp.mat);set(s.h.filelist,''String'',s.filenames,''Value'',1);set(s.h.textbox,''String'',s.parentpath);set(gcf,''UserData'',s)',...
   'HorizontalAlignment','center',...
   'Units','normalized',...
   'Position',[0.05 0.93 0.2 0.04],...
   'String','OpenDir');
h2 = uicontrol(fig,'BackgroundColor',get(fig,'Color'),...
   'Style','text',...
   'HorizontalAlignment','left',...
   'Units','normalized',...
   'Position',[0.3 0.93 0.6 0.04],...
   'String','Open Directory.');
h3 = uicontrol(fig,'BackgroundColor',[1 1 1],...
   'Style','Popupmenu',...
   'HorizontalAlignment','left',...
   'Units','normalized',...
   'Position',[0.7 0.85 0.2 0.04],...
   'String',{'GripOn';'GripOff';'GripTorPeak';'EndHold';'Control'});
h4 = uicontrol(fig,'BackgroundColor',[1 1 1],...
   'Max',1,...
   'Min',0,...
   'Style','Edit',...
   'HorizontalAlignment','left',...
   'Units','normalized',...
   'Position',[0.3 0.86 0.3 0.03],...
   'String',{'string';'filter'});
h5 = uicontrol(fig,'BackgroundColor',get(fig,'Color'),...
   'Style','checkbox',...
   'HorizontalAlignment','left',...
   'Units','normalized',...
   'Position',[0.2 0.86 0.1 0.03],...
   'String','Filter');


% s.h.pathlist    = h1;
s.h.filelist    = h1;
s.h.textbox     = h2;
s.h.settrigger  = h3;
set(fig,'UserData',s);