pathname        = '080907_50trials_combine';
% wcohpath        = fullfile(datapath,'wcoh',pathname);
wcohclssigpath  = fullfile(datapath,'wcohclssig',pathname);
refpath         = fullfile(datapath,'STA');
reffile1        = 'STA (Grip Onset (svwostim), smoothed Index Torque(N)).mat';
reffile2        = 'STA (Grip Onset (svwostim), smoothed Thumb Torque(N)).mat';

FOI             = [0 100];
% FOI             = [0 50];
TOI             = [-1 2];
% TOI             = [-1 3];
ForceLim        = [-5 15];
CLim            = [0 0.4];
CLimLFP         = [500000 300000000];
% CLimLFP         = [500000 500000000];
    

Expnames    = {'EitoT00102f';...
    'EitoT00205f';...
    'EitoT00211f';...
    'EitoT00216f';...
    'EitoT00218f';...
    'EitoT00219f';...
    'EitoT00401f';...
    'EitoT00402f';...
    'EitoT00407f';...
    'EitoT00409f';...
    'EitoT00410f';...
    'EitoT00501f';...
    'EitoT00502f';...
    'EitoT00504f';...
    'EitoT00509f';...
    'EitoT00510f';...
    'EitoT00603f';...
    'EitoT00607f';...
    'EitoT00609f';...
    'EitoT00612f';...
    'EitoT00613f';...
    'EitoT00614f';...
    'EitoT00702f';...
    'EitoT00704f';...
    'EitoT00709f';...
    'EitoT00712f';...
    'EitoT00713f';...
    'EitoT00802f';...
    'EitoT00805f';...
    'EitoT00808f';...
    'EitoT00816f';...
    'EitoT00901f';...
    'EitoT00902f';...
    'EitoT00904f';...
    'EitoT00910f';...
    'EitoT01001f';...
    'EitoT01003f';...
    'EitoT01004f';...
    'EitoT01005f';...
    'EitoT01006f';...
    'EitoT01009f';...
    'EitoT01013f';...
    'EitoT01015f';...
    'EitoT01016f';...
    'EitoT01101f';...
    'EitoT01202f';...
    'EitoT01203f';...
    'EitoT01302f';...
    'EitoT01305f';...
    'EitoT01308f';...
    'EitoT01310f';...
    'EitoT01402f';...
    'EitoT01403f';...
    'EitoT01408f';...
    'EitoT01409f';...
    'EitoT01414f';...
    'EitoT01503f';...
    'EitoT01506f';...
    'EitoT01508f';...
    'EitoT01513f';...
    'EitoT01601f';...
    'EitoT01604f';...
    'EitoT01606f';...
    'EitoT01608f';...
    'EitoT01701f';...
    'EitoT01702f';...
    'EitoT01704f';...
    'EitoT01714f';...
    'EitoT01716f';...
    'EitoT01801f';...
    'EitoT01802f';...
    'EitoT01803f';...
    'EitoT01806f';...
    'EitoT01901f';...
    'EitoT01902f';...
    'EitoT01907f';...
    'EitoT01908f';...
    'EitoT01911f';...
    'EitoT02101f';...
    'EitoT02103f';...
    'EitoT02104f';...
    'EitoT02105f';...
    'EitoT02108f';...
    'EitoT02110f';...
    'EitoT02301f';...
    'EitoT02302f';...
    'EitoT02303f';...
    'EitoT02403f';...
    'EitoT02407f';...
    'EitoT02411f';...
    'EitoT02502f';...
    'EitoT02511f';...
    'EitoT02513f';...
    'EitoT02601f';...
    'EitoT02604f';...
    'EitoT02605f';...
    'EitoT02608f';...
    'EitoT02702f';...
    'EitoT02703f';...
    'EitoT02705f';...
    'EitoT02706f';...
    'EitoT02707f';...
    'EitoT02710f'};
Expnames    = uiselect(Expnames);

% Expnames    = {'EitoT01908f'};

fieldname   = 'Field 1-subsample(uV)';
% fieldname   = 'Field 2-subsample';
% fieldname   = 'Field 3-subsample';

EMGnames   = {'FDI-subsample(uV)',...%
    '2DI-subsample(uV)',...
    '3DI-subsample(uV)',...
    '4DI-subsample(uV)',...
    'ADP-subsample(uV)',...
    'AbPB-subsample(uV)',...
    'AbDM-subsample(uV)',...
    'FDS-subsample(uV)',...
    'FDPr-subsample(uV)',...
    'FDPu-subsample(uV)',...
    'PL-subsample(uV)',...
    'FCR-subsample(uV)',...
    'FCU-subsample(uV)',...
    'AbPL-subsample(uV)',...
    'ED23-subsample(uV)',...
    'EDC-subsample(uV)',...
    'ECR-subsample(uV)',...
    'ECU-subsample(uV)',...
    'BRD-subsample(uV)',...
    'Biceps-subsample(uV)',...
    'Triceps-subsample(uV)'};



nExp    = length(Expnames);
nEMG    = length(EMGnames);

for iExp    = 1:nExp
    try
        Expname     = Expnames{iExp};

        fig = open('A4.fig');
        set(fig,'Name',Expname,...
            'FileName',Expname)
        for iEMG   = 1:nEMG
            EMGname     = EMGnames{iEMG};

%             wcohfilename        = fullfile(wcohpath,[Expname,'_',fieldname,'__',EMGname]);
            wcohclssigfilename  = fullfile(wcohclssigpath,[Expname,'_',fieldname,'__',EMGname]);
            reffilename1        = fullfile(refpath,Expname,reffile1);
            reffilename2        = fullfile(refpath,Expname,reffile2);

%             wcoh        = load(wcohfilename);
            wcohclssig  = load(wcohclssigfilename);
            ref1        = load(reffilename1);
            ref2        = load(reffilename2);

%             cxy     = wcoh.cxy;
%             cxysig  = wcohclssig.cxy;
            cxy     = wcohclssig.cxy;
            cxysig  = wcohclssig.clssig;


            if(iEMG==1)
                freq    = wcohclssig.freq;
                t       = wcohclssig.t;
                seg_tot = wcohclssig.cl.seg_tot;
                cl      = wcohclssig.cl.ch_c95;
                px      = wcohclssig.px;

                ref1y    = ref1.YData;
                ref1x    = ref1.XData;
                ref2y    = ref2.YData;
                ref2x    = ref2.XData;

                h   = subplot(11,4,1);
                pcolor(t,freq,px); shading flat
                set(h,'XLim',TOI,...
                    'YLim',FOI,...
                    'CLim',CLimLFP)
                title(h,fieldname)

                h   = subplot(11,4,2);
                plot(h,ref1x,ref1y,'-k');
                hold(h,'on')
                plot(h,ref2x,ref2y,':k');
                set(h,'XLim',TOI,...
                    'YLim',ForceLim);
                title({wcohclssigpath;Expname;datestr(now)})
            end

            h   = subplot(11,4,iEMG*2+1);
            pcolor(t,freq,cxy); shading flat
            set(h,'XLim',TOI,...
                'YLim',FOI,...
                'CLim',[cl CLim(2)])
            colormap(h,tmap2)
            title(EMGname)
            
            h   = subplot(11,4,iEMG*2+2);
            pcolor(t,freq,double(cxysig)); shading flat
            set(h,'XLim',TOI,...
                'YLim',FOI,...
                'CLim',[cl CLim(2)])

            colormap(h,tmap2)
%             if(iEMG==1)
%             colorbar('EastOutside')
%             end
            %         title('coh')
        end
        
        figpath = fullfile(datapath,'figures','wcoh');
        if(~exist(figpath))
            mkdir(figpath);
        end
%         print(fig)
        saveas(fig,fullfile(figpath,Expname),'jpg')
        saveas(fig,fullfile(figpath,Expname),'pdf')
        saveas(fig,fullfile(figpath,Expname),'fig')
        close(fig)

        disp([Expname, ' was printed out'])
    catch
        Expname     = Expnames{iExp};
        disp(['error occured in',Expname])
    end
end





